[package]
name = "pallet-group-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Common
polymesh-primitives = { path = "../../../../primitives", default-features = false}
polymesh-common-utilities = { path = "../../../common", default-features = false }

# Others
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", default_features = false }
sp-std = { version = "5.0.0", default_features = false }

[features]
default = ["std"]
std = [
	"serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"polymesh-primitives/std",
	"polymesh-common-utilities/std"
]
