[package]
name = "pallet-group-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Common
polymesh-primitives = { workspace = true, default-features = false}

# Others
serde = { version = "1.0.104", optional = true, features = ["derive"] }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
sp-api = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"serde",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"polymesh-primitives/std",
]
