[package]
name = "pallet-group-rpc-runtime-api"
version = "2.0.0"
authors = ["Anonymous"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
# Common
polymesh-primitives = { workspace = true, default-features = false }

# Others
serde = { version = "1.0.104", default-features = false, features = ["alloc", "derive"] }

# Substrate
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
sp-api = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive", "decode"] }

[features]
default = ["std"]
std = [
	"serde/std",
	"sp-api/std",
	"codec/std",
	"sp-std/std",
	"polymesh-primitives/std",
]
