ARG rustbase=1.74.0
FROM arm64v8/rust:${rustbase}-alpine

ARG toolchainversion=nightly-2023-12-01
ENV TOOLCHAIN="${toolchainversion}"

RUN apk add --no-cache \
        bash \
        ca-certificates \
        clang \
        clang-dev \
        cmake \
        g++ \
        gcc \
        jq \
        libressl-dev \
        make \
        pkgconfig \
        protobuf \
        rsync
RUN rustup toolchain install $TOOLCHAIN && \
  rustup default $TOOLCHAIN && \
  rustup target add wasm32-unknown-unknown

