[package]
name = "pallet-protocol-fee-rpc"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
jsonrpsee = { version = "0.22", features = ["server", "macros"] }
sp-api = { workspace = true, default-features = false }
sp-blockchain = { workspace = true }
sp-core = { workspace = true, default-features = false }
sp-rpc = { workspace = true }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }

node-rpc = { workspace = true }
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
pallet-protocol-fee-rpc-runtime-api = { workspace = true }

# General
serde = { version = "1.0.104", default-features = false, features = ["derive"] }
