[package]
name = "pallet-asset"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
# Common
polymesh-primitives = { workspace = true, default-features = false }
polymesh-primitives-derive = { workspace = true, default-features = false }

# Our Pallets
pallet-base = { workspace = true, default-features = false  }
pallet-external-agents = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-permissions = { workspace = true, default-features = false }
pallet-portfolio = { workspace = true, default-features = false }
pallet-statistics = { workspace = true, default-features = false }
polymesh-runtime-common = { workspace = true, default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }
serde_json = { version = "1.0.48", default-features = false }
rustc-hex = { version = "2.1.0", default-features = false }
hex-literal = "0.2.1"
arrayvec = { version = "0.7.1", default-features = false }
log = "0.4"

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-arithmetic = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }

# Only in STD
frame-benchmarking = { workspace = true, default-features = false, optional = true }

[features]
default = ["std"]
no_std = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-base/std",
    "pallet-identity/std",
    "pallet-portfolio/std",
    "pallet-timestamp/std",
    "pallet-external-agents/std",
    "pallet-statistics/std",
    "polymesh-primitives/std",
    "polymesh-runtime-common/std",
    "rustc-hex/std",
    "serde/std",
    "serde_derive",
    "sp-api/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",
    "sp-arithmetic/std"
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-external-agents/runtime-benchmarks",
    "pallet-permissions/runtime-benchmarks",
    "pallet-portfolio/runtime-benchmarks",
    "pallet-statistics/runtime-benchmarks",
    "polymesh-primitives/runtime-benchmarks",
    "polymesh-runtime-common/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
