[package]
name = "polymesh"
version = "8.0.0"
authors = ["PolymeshAssociation"]
build = "build.rs"
edition = "2021"

[[bin]]
name = "polymesh"
path = "src/main.rs"

# Path build to use our Substrate version from github, `branch = "polymesh-v8-monthly-2023-08"`.
[patch.crates-io]
frame-benchmarking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-benchmarking-cli = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-executive = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-support = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-election-provider-support = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-system = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-system-benchmarking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
frame-system-rpc-runtime-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-authority-discovery = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-authorship = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-babe = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-balances = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-contracts = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-election-provider-multi-phase = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-grandpa = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-im-online = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-indices = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-offences = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-preimage = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-insecure-randomness-collective-flip = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-scheduler = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-session = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-staking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-staking-runtime-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-staking-reward-curve = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
pallet-timestamp = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-authority-discovery = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-basic-authorship = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-block-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-chain-spec = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-cli = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-client-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-client-db = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus-babe = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus-babe-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus-epochs = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus-slots = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-executor = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus-grandpa = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-consensus-grandpa-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-keystore = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-network = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-network-common = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-network-sync = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-rpc-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-rpc-spec-v2 = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-service = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-telemetry = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-transaction-pool = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-transaction-pool-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-sync-state-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sc-offchain = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-application-crypto = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-arithmetic = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-authority-discovery = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-block-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-blockchain = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-consensus = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-consensus-babe = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-consensus-slots = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-core = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-debug-derive = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-externalities = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-consensus-grandpa = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-genesis-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-inherents = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-io = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-keystore = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-keyring = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-npos-elections = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-offchain = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-runtime = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-weights = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-runtime-interface = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-session = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-staking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-state-machine = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-std = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-storage = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-timestamp = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-tracing = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-transaction-pool = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-transaction-storage-proof = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-trie = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
sp-version = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
substrate-frame-rpc-system = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
substrate-prometheus-endpoint = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
substrate-build-script-utils = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
substrate-wasm-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }
substrate-test-utils = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2503-7" }

[workspace]
members = [
    "node-rpc",
    "pallets/asset",
    "pallets/base",
    "pallets/committee",
    "pallets/compliance-manager",
    "pallets/contracts",
    "pallets/corporate-actions",
    "pallets/external-agents",
    "pallets/group",
    "pallets/group/rpc",
    "pallets/group/rpc/runtime-api",
    "pallets/identity",
    "pallets/multisig",
    "pallets/nft",
    "pallets/pips",
    "pallets/protocol-fee",
    "pallets/protocol-fee/rpc",
    "pallets/protocol-fee/rpc/runtime-api",
    "pallets/relayer",
    "pallets/runtime/common",
    "pallets/runtime/develop",
    "pallets/runtime/mainnet",
    "pallets/runtime/testnet",
    "pallets/runtime/tests",
    "pallets/runtime/tests/exec_macro",
    "pallets/settlement",
    "pallets/statistics",
    "pallets/sto",
    "pallets/validators",
    "pallets/transaction-payment",
    "pallets/treasury",
    "pallets/utility",
    "pallets/weights",
    "primitives",
    "primitives_derive",
    "primitives/asset-metadata",
    "rpc",
    "rpc/runtime-api",
    "pallets/common",
]
exclude = [
    "contracts",
    "integration",
    "metadata-tools"
]

## Keep common dependencies here.
[workspace.dependencies]
# Our pallets
pallet-asset = { path = "pallets/asset", default-features = false }
pallet-base = { path = "pallets/base", default-features = false }
pallet-committee = { path = "pallets/committee", default-features = false }
pallet-compliance-manager = { path = "pallets/compliance-manager", default-features = false }
pallet-corporate-actions = { path = "pallets/corporate-actions", default-features = false }
pallet-external-agents = { path = "pallets/external-agents", default-features = false }
pallet-group = { path = "pallets/group", default-features = false }
pallet-identity = { path = "pallets/identity", default-features = false }
pallet-multisig = { path = "pallets/multisig", default-features = false }
pallet-nft = { path = "pallets/nft", default-features = false }
pallet-permissions = { path = "pallets/permissions", default-features = false }
pallet-pips = { path = "pallets/pips", default-features = false }
pallet-portfolio = { path = "pallets/portfolio", default-features = false }
pallet-protocol-fee = { path = "pallets/protocol-fee", default-features = false }
pallet-relayer = { path = "pallets/relayer", default-features = false }
pallet-sto = { path = "pallets/sto", default-features = false }
pallet-settlement = { path = "pallets/settlement", default-features = false }
pallet-validators = { path = "pallets/validators", default-features = false }
pallet-statistics = { path = "pallets/statistics", default-features = false }
pallet-transaction-payment = { path = "pallets/transaction-payment", default-features = false }
pallet-treasury = { path = "pallets/treasury", default-features = false }
pallet-utility = { path = "pallets/utility", default-features = false }
pallet-sudo = { path = "pallets/sudo", default-features = false }
polymesh-contracts = { path = "pallets/contracts", default-features = false }

# Common
polymesh-runtime-common = { path = "pallets/runtime/common", default-features = false }
polymesh-common-utilities = { path = "pallets/common", default-features = false }
polymesh-primitives = { path = "primitives", default-features = false }
polymesh-primitives-derive = { path = "primitives_derive", default-features = false }
polymesh-weights = { path = "pallets/weights/", default-features = false }

# RPC
node-rpc = { path = "rpc", default-features = false }
node-rpc-runtime-api = { path = "rpc/runtime-api", default-features = false }
pallet-group-rpc = { path = "pallets/group/rpc", default-features = false }
pallet-group-rpc-runtime-api = { path = "pallets/group/rpc/runtime-api", default-features = false }
pallet-protocol-fee-rpc = { path = "pallets/protocol-fee/rpc", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { path = "pallets/protocol-fee/rpc/runtime-api", default-features = false }
polymesh-node-rpc = { path = "node-rpc", default-features = false }

# Runtimes
polymesh-runtime-develop = { path = "pallets/runtime/develop" }
polymesh-runtime-mainnet = { path = "pallets/runtime/mainnet" }
polymesh-runtime-testnet = { path = "pallets/runtime/testnet" }

# Build tool
polymesh-build-tool = { path = "pallets/runtime/build_tool", default-features = false }

# Substrate
codec = { package = "parity-scale-codec", version = "3.7.4", default-features = false, features = ["derive", "max-encoded-len"] }
frame-support = { version = "40.1.0", default-features = false }
frame-system = { version = "40.2.0", default-features = false }
frame-system-benchmarking = { version = "40.0.1", default-features = false }
frame-system-rpc-runtime-api = { version = "36.0.0", default-features = false }
frame-election-provider-support = { version = "40.1.1", default-features = false }
frame-benchmarking = { version = "40.2.0", default-features = false }
frame-benchmarking-cli = { version = "48.0.0", default-features = false }
frame-executive = { version = "40.0.1", default-features = false }
pallet-authority-discovery = { version = "40.0.0", default-features = false }
pallet-authorship = { version = "40.0.0", default-features = false }
pallet-babe = { version = "40.0.0", default-features = false }
pallet-balances = { version = "41.1.1", default-features = false, features = ['insecure_zero_ed']}
pallet-contracts = { version = "40.1.0", default-features = false }
pallet-election-provider-multi-phase = { version = "39.2.0", default-features = false }
pallet-grandpa = { version = "40.0.0", default-features = false }
pallet-im-online = { version = "39.1.0", default-features = false }
pallet-indices = { version = "40.0.0", default-features = false }
pallet-offences = { version = "39.0.0", default-features = false }
pallet-preimage = { version = "40.0.0", default-features = false }
pallet-insecure-randomness-collective-flip = { version = "28.0.0", default-features = false }
pallet-scheduler = { version = "41.2.0", default-features = false }
pallet-session = { version = "40.0.1", default-features = false }
pallet-staking = { version = "40.1.1", default-features = false }
pallet-staking-runtime-api = { version = "26.0.0", default-features = false }
pallet-staking-reward-curve = { version = "12.0.0", default-features = false }
pallet-timestamp = { version = "39.0.0", default-features = false }
scale-info = { version = "2.11.6", default-features = false, features = ["derive"] }
sp-api = { version = "36.0.1", default-features = false }
sp-application-crypto = { version = "40.1.0", default-features = false }
sp-arithmetic = { version = "26.1.0", default-features = false }
sp-authority-discovery = { version = "36.0.0", default-features = false }
sp-block-builder = { version = "36.0.0", default-features = false }
sp-blockchain = { version = "39.0.0", default-features = false }
sp-consensus = { version = "0.42.0", default-features = false }
sp-consensus-babe = { version = "0.42.1", default-features = false }
sp-consensus-grandpa = { version = "23.1.0", default-features = false }
sp-consensus-slots = { version = "0.42.1", default-features = false }
sp-core = { version = "36.1.0", default-features = false }
sp-debug-derive = { version = "14.0.0", default-features = false }
sp-genesis-builder = { version = "0.17.0", default-features = false }
sp-inherents = { version = "36.0.0", default-features = false }
sp-io = { version = "40.0.1", default-features = false }
sp-keyring = { version = "41.0.0", default-features = false }
sp-keystore = { version = "0.42.0", default-features = false }
sp-npos-elections = { version = "36.2.0", default-features = false }
sp-offchain = { version = "36.0.0", default-features = false }
sp-rpc = { version = "34.0.0", default-features = false }
sp-runtime = { version = "41.1.0", default-features = false }
sp-runtime-interface = { version = "29.0.1", default-features = false }
sp-session = { version = "38.1.0", default-features = false }
sp-staking = { version = "38.0.0", default-features = false }
sp-std = { version = "14.0.0", default-features = false }
sp-timestamp = { version = "36.0.0", default-features = false }
sp-tracing = { version = "17.1.0", default-features = false }
sp-transaction-storage-proof = { version = "36.1.0", default-features = false }
sp-transaction-pool = { version = "36.0.0", default-features = false }
sp-weights = { version = "31.1.0", default-features = false }
sp-version = { version = "39.0.0", default-features = false }
substrate-test-utils = { version = "3.0.0", default-features = false }
substrate-wasm-builder = { version = "26.0.1", default-features = false }
substrate-frame-rpc-system = { version = "44.0.0", default-features = false }

# Substrate client deps.
sc-authority-discovery = "0.50.0"
sc-basic-authorship = "0.49.0"
sc-chain-spec = "43.0.0"
sc-cli = { version = "0.52.0" }
sc-client-api = "39.0.0"
sc-client-db = { version = "0.46.0", default-features = false }
sc-consensus = "0.49.0"
sc-consensus-babe = "0.50.0"
sc-consensus-babe-rpc = "0.50.0"
sc-consensus-epochs = { version = "0.49.0" }
sc-consensus-grandpa = "0.35.0"
sc-consensus-grandpa-rpc = "0.35.0"
sc-consensus-slots = "0.49.0"
sc-executor = { version = "0.42.0" }
sc-network = "0.50.0"
sc-network-common = { version = "0.48.0" }
sc-network-sync = { version = "0.49.0" }
sc-rpc = "45.0.0"
sc-rpc-api = { version = "0.49.0" }
sc-rpc-spec-v2 = { version = "0.50.0" }
sc-service = { version = "0.51.0" }
sc-telemetry = "28.1.0"
sc-transaction-pool = "39.0.0"
sc-transaction-pool-api = { version = "39.0.0" }
sc-sync-state-rpc = { version = "0.50.0" }
sc-offchain = { version = "45.0.0" }

# Crypto
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand_chacha = { version = "0.3", default-features = false }

[dependencies]
pallet-asset = { workspace = true }
pallet-balances = { workspace = true, default-features = false, features = ["insecure_zero_ed"] }
pallet-committee = { workspace = true, default-features = false }
pallet-corporate-actions = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-group = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-multisig = { workspace = true, default-features = false }
pallet-permissions = { workspace = true, default-features = false }
pallet-pips = { workspace = true, default-features = false }
pallet-protocol-fee = { workspace = true, default-features = false }
pallet-staking = { workspace = true, default-features = false }
pallet-staking-runtime-api = { workspace = true, default-features = false }
pallet-validators = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
polymesh-contracts = { workspace = true, default-features = false }
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
polymesh-runtime-common = { workspace = true, default-features = false }

# RPC
node-rpc = { workspace = true }
node-rpc-runtime-api = { workspace = true }
pallet-group-rpc = { workspace = true }
pallet-group-rpc-runtime-api = { workspace = true }
pallet-protocol-fee-rpc = { workspace = true }
pallet-protocol-fee-rpc-runtime-api = { workspace = true }
polymesh-node-rpc = { workspace = true }

# Runtimes
polymesh-runtime-develop = { workspace = true }
polymesh-runtime-mainnet = { workspace = true }
polymesh-runtime-testnet = { workspace = true }

## General
futures = "0.3.21"
jsonrpsee = { version = "0.24.9", features = ["server"] }
log = "0.4"
serde = { version = "1.0.136", default-features = false, features = ["alloc", "derive"] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
clap = { version = "4.0.9", features = ["derive"] }
rustc-hex = "2.1.0"

# Substrate client deps.
sc-authority-discovery = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-chain-spec = { workspace = true }
sc-cli = { workspace = true }
sc-client-api = { workspace = true }
sc-client-db = { workspace = true, default-features = false }
sc-consensus = { workspace = true }
sc-consensus-babe = { workspace = true }
sc-consensus-slots = { workspace = true }
sc-executor = { workspace = true }
sc-network = { workspace = true }
sc-network-common = { workspace = true }
sc-network-sync = { workspace = true }
sc-rpc = { workspace = true }
sc-service = { workspace = true }
sc-telemetry = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sc-sync-state-rpc = { workspace = true }
sc-offchain = { workspace = true }
grandpa = { package = "sc-consensus-grandpa", version = "0.35.0" }

# Substrate
codec = { package = "parity-scale-codec", version = "3.7.4", default-features = false, features = ["derive", "max-encoded-len"] }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
pallet-babe = { workspace = true }
pallet-im-online = { workspace = true }
pallet-indices = { workspace = true }
pallet-session = { workspace = true }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", version = "0.17.2" }
sp-api = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-keyring = { workspace = true }
sp-core = { workspace = true }
sp-genesis-builder = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-transaction-storage-proof = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-timestamp = { workspace = true }
sp-session = { workspace = true }
sp-transaction-pool = { workspace = true }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { workspace = true }
frame-benchmarking-cli = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { version = "11.0.0" }

[features]
default = ["std"]
disable_fees = [
    "pallet-transaction-payment/disable_fees", 
    "polymesh-runtime-develop/disable_fees", 
    "polymesh-runtime-mainnet/disable_fees",
    "polymesh-runtime-testnet/disable_fees",
]
running-ci = [ "polymesh-runtime-develop/running-ci" ]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-benchmarking-cli/runtime-benchmarks",
    "sc-client-db/runtime-benchmarks",
    "polymesh-runtime-develop/runtime-benchmarks",
]

# Only build a "ci" runtime.
ci-runtime = [ "polymesh-runtime-develop/ci-runtime" ]

std = [
    "serde/std"
]
