[package]
name = "polymesh"
version = "8.0.0"
authors = ["PolymeshAssociation"]
build = "build.rs"
edition = "2021"

[[bin]]
name = "polymesh"
path = "src/bin/main.rs"

[patch.crates-io]
# Patch this to avoid duplicate deps (subxt uses this dep).
sp-crypto-hashing = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }

# DART
# Curve tree dependencies
#curve_tree_bulletproofs = { package = "bulletproofs", path = "../curve-trees/bulletproofs" }
#curve_tree_relations = { package = "relations", path = "../curve-trees/relations" }
#ark-ec-divisors = { package = "ark-ec-divisors", path = "../curve-trees/ark-ec-divisors"}
#ark-dlog-gadget = { package = "ark-dlog-gadget", path = "../curve-trees/ark-dlog-gadget"}
# If want to pull code for curve-trees from git, comment above 2 relations and uncomment below 2
curve_tree_bulletproofs = { package = "bulletproofs", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }
curve_tree_relations = { package = "relations", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }
ark-ec-divisors = { package = "ark-ec-divisors", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }
ark-dlog-gadget = { package = "ark-dlog-gadget", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }

#dock_crypto_utils = { path = "../crypto/utils" }
#schnorr_pok = { path = "../crypto/schnorr_pok" }
dock_crypto_utils = { git = "https://github.com/PolymeshAssociation/crypto", branch = "main" }
schnorr_pok = { git = "https://github.com/PolymeshAssociation/crypto", branch = "main" }

#polymesh-dart = { path = "../polymesh-dart" }
#polymesh-dart-bp = { path = "../polymesh-dart/dart-bp" }
#polymesh-dart-common = { path = "../polymesh-dart/dart-common" }
polymesh-dart = { git = "https://github.com/PolymeshAssociation/polymesh-dart", branch = "main" }
polymesh-dart-bp = { git = "https://github.com/PolymeshAssociation/polymesh-dart", branch = "main" }
polymesh-dart-common = { git = "https://github.com/PolymeshAssociation/polymesh-dart", branch = "main" }

# Polymesh changes to Arkworks.
#ark-serialize = { path = "../arkworks-algebra/serialize" }
#ark-ec = { path = "../arkworks-algebra/ec" }
#ark-ff = { path = "../arkworks-algebra/ff" }
#ark-pallas = { path = "../arkworks-algebra/curves/pallas" }
#ark-vesta = { path = "../arkworks-algebra/curves/vesta" }
#ark-helios = { path = "../arkworks-algebra/curves/helios" }
#ark-selene = { path = "../arkworks-algebra/curves/selene" }
#ark-wei25519 = { path = "../arkworks-algebra/curves/wei25519" }
#ark-curve25519 = { path = "../arkworks-algebra/curves/curve25519" }
#ark-ed25519 = { path = "../arkworks-algebra/curves/ed25519" }
ark-serialize = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ec = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ff = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-pallas = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-vesta = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-bls12-381 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-bls12-377 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-bn254 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-helios = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-selene = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-wei25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-curve25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ed25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }

[workspace]
members = [
    "eth-rpc",
    "node-rpc",
    "worker",
    "worker/protocol/common",
    "worker/protocol/dart-v0",
    "pallets/asset",
    "pallets/base",
    "pallets/committee",
    "pallets/compliance-manager",
    "pallets/confidential-assets",
    "pallets/confidential-assets/host-functions",
    "pallets/contracts",
    "pallets/corporate-actions",
    "pallets/external-agents",
    "pallets/group",
    "pallets/group/rpc",
    "pallets/group/rpc/runtime-api",
    "pallets/identity",
    "pallets/multisig",
    "pallets/nft",
    "pallets/pips",
    "pallets/protocol-fee",
    "pallets/protocol-fee/rpc",
    "pallets/protocol-fee/rpc/runtime-api",
    "pallets/relayer",
    "pallets/runtime/common",
    "pallets/runtime/develop",
    "pallets/runtime/mainnet",
    "pallets/runtime/testnet",
    "pallets/runtime/tests",
    "pallets/runtime/tests/exec_macro",
    "pallets/settlement",
    "pallets/statistics",
    "pallets/sto",
    "pallets/validators",
    "pallets/transaction-payment",
    "pallets/treasury",
    "pallets/utility",
    "pallets/weights",
    "primitives",
    "primitives_derive",
    "primitives/asset-metadata",
    "rpc",
    "rpc/runtime-api",
]
exclude = ["contracts", "integration", "metadata-tools"]

[workspace.package]
version = "8.0.0"
authors = ["PolymeshAssociation"]
edition = "2021"
repository = "https://github.com/PolymeshAssociation/Polymesh"
homepage = "https://github.com/PolymeshAssociation/Polymesh"

## Keep common dependencies here.
[workspace.dependencies]
# Polymesh worker host functions and protocols.
polymesh-worker = { path = "worker", default-features = false }
polymesh-worker-protocol-common = { path = "worker/protocol/common", default-features = false }
polymesh-worker-protocol-dart-v0 = { path = "worker/protocol/dart-v0", default-features = false }

# Polkavm for protocol workers.
polkavm = { version = "0.32", default-features = false }
polkavm-derive = { version = "0.32", default-features = false }

# Our pallets
pallet-asset = { path = "pallets/asset", default-features = false }
pallet-base = { path = "pallets/base", default-features = false }
pallet-committee = { path = "pallets/committee", default-features = false }
pallet-compliance-manager = { path = "pallets/compliance-manager", default-features = false }
pallet-confidential-assets = { path = "pallets/confidential-assets", default-features = false }
polymesh-dart-host-functions = { path = "pallets/confidential-assets/host-functions/", default-features = false }
pallet-corporate-actions = { path = "pallets/corporate-actions", default-features = false }
pallet-external-agents = { path = "pallets/external-agents", default-features = false }
pallet-group = { path = "pallets/group", default-features = false }
pallet-identity = { path = "pallets/identity", default-features = false }
pallet-multisig = { path = "pallets/multisig", default-features = false }
pallet-nft = { path = "pallets/nft", default-features = false }
pallet-permissions = { path = "pallets/permissions", default-features = false }
pallet-pips = { path = "pallets/pips", default-features = false }
pallet-portfolio = { path = "pallets/portfolio", default-features = false }
pallet-protocol-fee = { path = "pallets/protocol-fee", default-features = false }
pallet-relayer = { path = "pallets/relayer", default-features = false }
pallet-sto = { path = "pallets/sto", default-features = false }
pallet-settlement = { path = "pallets/settlement", default-features = false }
pallet-validators = { path = "pallets/validators", default-features = false }
pallet-statistics = { path = "pallets/statistics", default-features = false }
polymesh-transaction-payment = { path = "pallets/transaction-payment", default-features = false }
pallet-treasury = { path = "pallets/treasury", default-features = false }
pallet-utility = { path = "pallets/utility", default-features = false }
polymesh-contracts = { path = "pallets/contracts", default-features = false }

# Common
polymesh-runtime-common = { path = "pallets/runtime/common", default-features = false }
polymesh-primitives = { path = "primitives", default-features = false }
polymesh-primitives-derive = { path = "primitives_derive", default-features = false }
polymesh-weights = { path = "pallets/weights/", default-features = false }

# RPC
node-rpc = { path = "rpc", default-features = false }
node-rpc-runtime-api = { path = "rpc/runtime-api", default-features = false }
pallet-group-rpc = { path = "pallets/group/rpc", default-features = false }
pallet-group-rpc-runtime-api = { path = "pallets/group/rpc/runtime-api", default-features = false }
pallet-protocol-fee-rpc = { path = "pallets/protocol-fee/rpc", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { path = "pallets/protocol-fee/rpc/runtime-api", default-features = false }
polymesh-node-rpc = { path = "node-rpc", default-features = false }

# Runtimes
polymesh-runtime-develop = { path = "pallets/runtime/develop" }
polymesh-runtime-mainnet = { path = "pallets/runtime/mainnet" }
polymesh-runtime-testnet = { path = "pallets/runtime/testnet" }

# Build tool
polymesh-build-tool = { path = "pallets/runtime/build_tool", default-features = false }

# SCALE Codec deps.
codec = { package = "parity-scale-codec", version = "3.7.4", default-features = false, features = [
    "derive",
    "max-encoded-len",
] }
scale-info = { version = "2.11.6", default-features = false, features = [
    "derive",
] }
bounded-collections = { version = "0.3.2", default-features = false }

# Substrate pallet/runtime deps.
frame-benchmarking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-benchmarking-cli = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-executive = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-metadata-hash-extension = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-support = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-election-provider-support = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-system = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-system-benchmarking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
frame-system-rpc-runtime-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
mmr-gadget = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
mmr-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-authority-discovery = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-authorship = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-babe = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-balances = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false, features = [
    'insecure_zero_ed',
] }
pallet-beefy = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-beefy-mmr = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-contracts = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-election-provider-multi-phase = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-grandpa = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-im-online = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-indices = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-mmr = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-offences = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-preimage = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-revive = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-revive-fixtures = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-scheduler = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-session = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-session-benchmarking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-staking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-staking-runtime-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-staking-reward-curve = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-sudo = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-transaction-payment = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
pallet-timestamp = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-application-crypto = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-arithmetic = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-authority-discovery = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-block-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-blockchain = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-consensus = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-consensus-babe = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-consensus-beefy = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-consensus-slots = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-core = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-crypto-hashing = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sp-debug-derive = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-externalities = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-consensus-grandpa = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-genesis-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-inherents = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-io = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-keystore = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-keyring = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-mmr-primitives = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-npos-elections = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-offchain = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-runtime = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-weights = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-runtime-interface = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-session = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-staking = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-state-machine = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-std = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-storage = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-timestamp = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-tracing = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-transaction-pool = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-transaction-storage-proof = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-trie = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sp-version = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }

# Substrate client/node deps.
sc-authority-discovery = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-basic-authorship = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-block-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-chain-spec = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-cli = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-client-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-client-db = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603", default-features = false }
sc-consensus = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-babe = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-babe-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-beefy = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-beefy-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-epochs = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-slots = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-executor = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-grandpa = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-consensus-grandpa-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-keystore = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-network = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-network-common = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-network-sync = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-rpc-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-rpc-spec-v2 = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-service = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-storage-monitor = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-sync-state-rpc = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-sysinfo = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-telemetry = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-transaction-pool = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-transaction-pool-api = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
sc-offchain = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
substrate-frame-rpc-system = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
substrate-prometheus-endpoint = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
substrate-wasm-builder = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
substrate-test-utils = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
substrate-build-script-utils = { git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }
prometheus-endpoint = { package = "substrate-prometheus-endpoint", git = "https://github.com/PolymeshAssociation/polkadot-sdk", branch = "polymesh-v8-stable2603" }

# Crypto
rand = { version = "0.8", default-features = false }
rand_core = { version = "0.6", default-features = false }
rand_chacha = { version = "0.3", default-features = false }

# DART
polymesh-dart = { version = "0.1.0", default-features = false }
polymesh-dart-common = { version = "0.1.0", default-features = false }
ark-ec = { version = "0.5", default-features = false }
ark-std = { version = "0.5", default-features = false }

[dependencies]
pallet-asset = { workspace = true }
pallet-committee = { workspace = true, default-features = false }
pallet-confidential-assets = { workspace = true, default-features = false }
polymesh-dart-host-functions = { workspace = true, default-features = false }
pallet-corporate-actions = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-group = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-multisig = { workspace = true, default-features = false }
pallet-permissions = { workspace = true, default-features = false }
pallet-pips = { workspace = true, default-features = false }
pallet-protocol-fee = { workspace = true, default-features = false }
pallet-validators = { workspace = true, default-features = false }
polymesh-transaction-payment = { workspace = true, default-features = false }
polymesh-contracts = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
polymesh-runtime-common = { workspace = true, default-features = false }

# RPC
node-rpc = { workspace = true }
node-rpc-runtime-api = { workspace = true }
pallet-group-rpc = { workspace = true }
pallet-group-rpc-runtime-api = { workspace = true }
pallet-protocol-fee-rpc = { workspace = true }
pallet-protocol-fee-rpc-runtime-api = { workspace = true }
polymesh-node-rpc = { workspace = true }

# Runtimes
polymesh-runtime-develop = { workspace = true }
polymesh-runtime-mainnet = { workspace = true }
polymesh-runtime-testnet = { workspace = true }

## General
futures = "0.3.21"
jsonrpsee = { version = "0.24.9", features = ["server"] }
log = "0.4"
serde = { version = "1.0.136", default-features = false, features = [
    "alloc",
    "derive",
] }
serde_json = { version = "1.0", features = ["arbitrary_precision"] }
clap = { version = "4.0.9", features = ["derive"] }
rustc-hex = "2.1.0"
array-bytes = { version = "6.2.2", default-features = false }

# Substrate client deps.
mmr-gadget = { workspace = true }
mmr-rpc = { workspace = true }
sc-authority-discovery = { workspace = true }
sc-basic-authorship = { workspace = true }
sc-chain-spec = { workspace = true }
sc-cli = { workspace = true }
sc-client-api = { workspace = true }
sc-client-db = { workspace = true, default-features = false }
sc-consensus = { workspace = true }
sc-consensus-babe = { workspace = true }
sc-consensus-beefy = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-consensus-slots = { workspace = true }
sc-executor = { workspace = true }
sc-network = { workspace = true }
sc-network-common = { workspace = true }
sc-network-sync = { workspace = true }
sc-rpc = { workspace = true }
sc-service = { workspace = true }
sc-storage-monitor = { workspace = true }
sc-sync-state-rpc = { workspace = true }
sc-sysinfo = { workspace = true }
sc-telemetry = { workspace = true }
sc-transaction-pool = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sc-offchain = { workspace = true }

# Substrate
codec = { package = "parity-scale-codec", version = "3.7.4", default-features = false, features = [
    "derive",
    "max-encoded-len",
] }
frame-metadata-hash-extension = { workspace = true, default-features = false }
frame-support = { workspace = true }
frame-system = { workspace = true }
frame-system-rpc-runtime-api = { workspace = true }
pallet-babe = { workspace = true }
pallet-balances = { workspace = true, default-features = false, features = [
    "insecure_zero_ed",
] }
pallet-im-online = { workspace = true }
pallet-indices = { workspace = true }
pallet-revive = { workspace = true }
pallet-session = { workspace = true }
pallet-staking = { workspace = true, default-features = false }
pallet-staking-runtime-api = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
prometheus-endpoint = { workspace = true, default-features = false }
sp-api = { workspace = true }
sp-authority-discovery = { workspace = true }
sp-block-builder = { workspace = true }
sp-blockchain = { workspace = true }
sp-consensus = { workspace = true }
sp-consensus-babe = { workspace = true }
sp-consensus-beefy = { workspace = true }
sp-consensus-slots = { workspace = true }
sp-keyring = { workspace = true }
sp-core = { workspace = true }
sp-genesis-builder = { workspace = true }
sp-inherents = { workspace = true }
sp-io = { workspace = true }
sp-mmr-primitives = { workspace = true }
sp-transaction-storage-proof = { workspace = true }
sp-offchain = { workspace = true }
sp-runtime = { workspace = true }
sp-timestamp = { workspace = true }
sp-session = { workspace = true }
sp-transaction-pool = { workspace = true }

# These dependencies are used for runtime benchmarking
frame-benchmarking = { workspace = true }
frame-benchmarking-cli = { workspace = true }

[build-dependencies]
substrate-build-script-utils = { workspace = true }

[features]
default = ["std"]
disable_fees = [
    "polymesh-transaction-payment/disable_fees",
    "polymesh-runtime-develop/disable_fees",
    "polymesh-runtime-mainnet/disable_fees",
    "polymesh-runtime-testnet/disable_fees",
]
running-ci = ["polymesh-runtime-develop/running-ci"]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "frame-benchmarking-cli/runtime-benchmarks",
    "sc-client-db/runtime-benchmarks",
    "polymesh-runtime-develop/runtime-benchmarks",
    "polymesh-runtime-testnet/runtime-benchmarks",
    "polymesh-runtime-mainnet/runtime-benchmarks",
    "polymesh-dart-host-functions/runtime-benchmarks",
]

# Only build a "ci" runtime.
ci-runtime = ["polymesh-runtime-develop/ci-runtime"]

metadata-hash = [
    "polymesh-runtime-develop/metadata-hash",
    "polymesh-runtime-mainnet/metadata-hash",
    "polymesh-runtime-testnet/metadata-hash",
]

std = [
		"polymesh-dart-host-functions/std",
    "serde/std"
]
