[package]
name = "polymesh-precompiles"
version = "0.0.1"
authors = ["Polymesh Association"]
license-file = "../LICENSE"
repository = "https://github.com/PolymeshAssociation/Polymesh"
description = "Polymesh Precompiles"
edition = "2021"

[dependencies]
# Substrate pallets
alloy-core = { workspace = true, features = ["rlp", "sol-types"] }

[features]
default = ["std"]
no_std = []

std = []
