[package]
name = "node-rpc"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
jsonrpsee = { version = "0.16.2", features = ["server", "macros"] }
sp-api = { workspace = true, default-features = false }
sp-blockchain = { workspace = true }
sp-core = { workspace = true, default-features = false }
sp-rpc = { workspace = true }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-weights = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }

node-rpc-runtime-api = { workspace = true, default-features = false }

pallet-compliance-manager = { workspace = true, default-features = false }
pallet-pips = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }

pallet-portfolio = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }

# Others
serde = { version = "1.0.104", default-features = false, features = ["alloc", "derive"] }

[features]
default = ["std"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "node-rpc-runtime-api/std",
    "pallet-identity/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-transaction-payment/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-api/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-weights/std",
]
