[package]
name = "polymesh_ink_upgrade_tracker"
version = "1.0.0"
authors = ["PolymeshAssociation"]
edition = "2021"
license = "Apache-2.0"
description = "Upgrade tracker contract for Upgradable Polymesh Ink! API"
keywords = ["polymesh", "ink", "blockchain", "substrate", "upgradable"]
repository = "https://github.com/PolymeshAssociation/Polymesh"
homepage = "https://github.com/PolymeshAssociation/Polymesh"

[dependencies]
ink_primitives = { version = "3.0", default-features = false }
ink_prelude = { version = "3.0", default-features = false }
ink_metadata = { version = "3.0", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0", default-features = false }
ink_storage = { version = "3.0", default-features = false }
ink_lang = { version = "3.0", default-features = false }
ink_lang_codegen = { version = "3.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

polymesh-api = { version = "0.3.8", default-features = false, features = ["ink"] }

[lib]
name = "polymesh_ink_upgrade_tracker"
path = "src/lib.rs"
crate-type = [
    # Used for normal contract Wasm blobs.
    "cdylib",
    # Used for ABI generation.
    "rlib",
]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info/std",
    "polymesh-api/std",
]
ink-as-dependency = []
