[package]
name = "polymesh-runtime-tests"
version = "1.0.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
node-rpc-runtime-api = { workspace = true, default-features = false }
pallet-asset = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-base = { workspace = true, default-features = false }
pallet-bridge = { workspace = true, default-features = false }
pallet-committee = { workspace = true, default-features = false }
pallet-compliance-manager = { workspace = true, default-features = false }
pallet-corporate-actions = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-group = { workspace = true, default-features = false }
pallet-group-rpc-runtime-api = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false, features = ["no_cdd"] }
pallet-multisig = { workspace = true, default-features = false }
pallet-nft = { workspace = true, default-features = false }
pallet-permissions = { workspace = true, default-features = false }
pallet-pips = { workspace = true, default-features = false }
pallet-portfolio = { workspace = true, default-features = false }
pallet-protocol-fee = { workspace = true, default-features = false }
pallet-protocol-fee-rpc-runtime-api = { workspace = true, default-features = false }
pallet-relayer = { workspace = true, default-features = false }
pallet-settlement = { workspace = true, default-features = false }
pallet-staking = { workspace = true, default-features = false }
pallet-staking-rpc-runtime-api = { workspace = true, default-features = false }
pallet-statistics = { workspace = true, default-features = false }
pallet-sto = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
pallet-treasury = { workspace = true, default-features = false }
pallet-utility = { workspace = true, default-features = false }
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-contracts = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
polymesh-runtime-common = { workspace = true, default-features = false, features = ["testing"] }
polymesh-runtime-develop = { workspace = true }
polymesh-weights = { workspace = true, default-features = false }
polymesh-exec-macro = { path = "exec_macro" }

# General
serde = { version = "1.0.104", default-features = false }
rand = { version = "0.7.3", default-features = false }
chrono = { version = "0.4", default-features = false }
hex-literal = "0.3.0"
smallvec = "1.4.1"
lazy_static = "1.4.0"
parking_lot = "0.12.0"
env_logger = "0.7"
serde_json = '1.0.48'
log = "0.4.8"

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
frame-benchmarking = { version = "4.0.0-dev", optional = true }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", default-features = false }
frame-election-provider-support = { version = "4.0.0-dev", default-features = false }
ink_primitives = { git = "https://github.com/paritytech/ink", tag = "v2.1.0", default-features = false }
pallet-authority-discovery = { version = "4.0.0-dev", default-features = false }
pallet-authorship = { version = "4.0.0-dev", default-features = false }
pallet-babe = { version = "4.0.0-dev", default-features = false }
pallet-contracts = { version = "4.0.0-dev", default-features = false }
pallet-contracts-primitives = { version = "7.0.0", default-features = false }
pallet-election-provider-multi-phase = { version = "4.0.0-dev", default-features = false }
pallet-executive = { package = "frame-executive", version = "4.0.0-dev", default-features = false }
pallet-grandpa = { version = "4.0.0-dev", default-features = false }
pallet-im-online = { version = "4.0.0-dev", default-features = false }
pallet-indices = { version = "4.0.0-dev", default-features = false }
pallet-offences = { version = "4.0.0-dev", default-features = false }
pallet-preimage = { version = "4.0.0-dev", default-features = false }
pallet-insecure-randomness-collective-flip = { version = "4.0.0-dev", default-features = false }
pallet-scheduler = { version = "4.0.0-dev", default-features = false }
pallet-session = { version = "4.0.0-dev", default-features = false, features = ["historical"] }
pallet-staking-reward-curve = { version = "4.0.0-dev", default-features = false }
pallet-timestamp = { version = "4.0.0-dev", default-features = false }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-api = { version = "4.0.0-dev", default-features = false }
sp-arithmetic = { version = "6.0.0", default-features = false }
sp-authority-discovery = { version = "4.0.0-dev", default-features = false }
sp-block-builder = { version = "4.0.0-dev", default-features = false }
sp-consensus-babe = { version = "0.10.0-dev", default-features = false }
sp-consensus-grandpa = { version = "4.0.0-dev", default-features = false }
sp-core = { version = "7.0.0", default-features = false }
sp-inherents = { version = "4.0.0-dev", default-features = false }
sp-io = { version = "7.0.0", default-features = false }
sp-npos-elections = { version = "4.0.0-dev", default-features = false }
sp-offchain = { version = "4.0.0-dev", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false }
sp-session = { version = "4.0.0-dev", default-features = false }
sp-staking = { version = "4.0.0-dev", default-features = false }
sp-std = { version = "5.0.0", default-features = false }
sp-transaction-pool = { version = "4.0.0-dev", default-features = false }
sp-version = { version = "5.0.0", default-features = false }
sp-keyring = { version = "7.0.0" }
substrate-test-utils = { version = "4.0.0-dev", default-features = false }

[dev-dependencies]
libsecp256k1 = { version = "0.7", default-features = false }
wat = "1.0"
sp-tracing = { version = "6.0.0", default-features = false, features = ["std"] }

[features]
default = ["std", "testing", "equalize"]

default_identity = [ "polymesh-common-utilities/default_identity" ]

testing = []
equalize = []
only-staking = []

# Backends
u64_backend = ["polymesh-primitives/u64_backend"]

no_std = [
    "u64_backend"
]

std = [
    "u64_backend",
    "frame-support/std",
    "frame-system/std",
    "frame-election-provider-support/std",
    "ink_primitives/std",
    "pallet-asset/std",
    "pallet-authorship/std",
    "pallet-base/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "pallet-sto/std",
    "pallet-bridge/std",
    "pallet-committee/std",
    "pallet-compliance-manager/std",
    "pallet-contracts/std",
    "pallet-corporate-actions/std",
    "pallet-election-provider-multi-phase/std",
    "pallet-external-agents/std",
    "polymesh-weights/std",
    "pallet-group-rpc-runtime-api/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-multisig/std",
    "pallet-nft/std",
    "pallet-permissions/std",
    "pallet-preimage/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-relayer/std",
    "pallet-insecure-randomness-collective-flip/std",
    "pallet-scheduler/std",
    "pallet-session/std",
    "pallet-staking/std",
    "pallet-statistics/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-treasury/std",
    "pallet-sudo/std",
    "polymesh-common-utilities/std",
    "polymesh-primitives/std",
    "polymesh-runtime-common/std",
    "polymesh-contracts/std",
    "polymesh-weights/std",
    "serde/std",
    "sp-arithmetic/std",
    "sp-core/std",
    "sp-io/std",
    "sp-npos-elections/std",
    "sp-runtime/std",
    "sp-staking/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
]
try-runtime = []
