[package]
name = "pallet-protocol-fee-rpc-runtime-api"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }

# General
serde = { version = "1.0.104", default-features = false, features = ["alloc", "derive"] }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
sp-api = { workspace = true, default-features = false}
sp-runtime = { workspace = true, default-features = false}
scale-info = { workspace = true, default-features = false, features = ["derive", "decode"] }

[features]
default = ["std"]
std = [
    "serde/std",
    "sp-api/std",
    "codec/std",
    "sp-runtime/std",
    "scale-info/std",
    "polymesh-primitives/std",
    "polymesh-common-utilities/std",
]
