[package]
name = "polymesh-runtime-develop"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Common
polymesh-runtime-common = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
polymesh-weights = { workspace = true, default-features = false }
polymesh-dart = { workspace = true, default-features = false }

# Our pallets
pallet-asset = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-base = { workspace = true, default-features = false }
pallet-committee = { workspace = true, default-features = false }
pallet-compliance-manager = { workspace = true, default-features = false }
pallet-confidential-assets = { workspace = true, default-features = false }
pallet-corporate-actions = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-group = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-multisig = { workspace = true, default-features = false }
pallet-nft = { workspace = true, default-features = false }
pallet-permissions = { workspace = true, default-features = false }
pallet-pips = { workspace = true, default-features = false }
pallet-portfolio = { workspace = true, default-features = false }
pallet-protocol-fee = { workspace = true, default-features = false }
pallet-relayer = { workspace = true, default-features = false }
pallet-sto = { workspace = true, default-features = false }
pallet-settlement = { workspace = true, default-features = false }
pallet-validators = { workspace = true, default-features = false }
pallet-statistics = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }
pallet-treasury = { workspace = true, default-features = false }
pallet-utility = { workspace = true, default-features = false }
pallet-precompiles = { workspace = true, default-features = false }
polymesh-transaction-payment = { workspace = true, default-features = false }

# Others
serde = { version = "1.0.104", default-features = false }
log = { version = "0.4.8", default-features = false }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-inherents = { workspace = true, default-features = false }
sp-offchain = { workspace = true, default-features = false }
sp-staking = { workspace = true, default-features = false }
sp-consensus-babe = { workspace = true, default-features = false }
sp-consensus-beefy = { workspace = true, default-features = false }
sp-consensus-grandpa = { workspace = true, default-features = false }
sp-session = { workspace = true, default-features = false }
sp-authority-discovery = { workspace = true, default-features = false }
sp-transaction-pool = { workspace = true, default-features = false }
sp-block-builder = { workspace = true, default-features = false }
sp-arithmetic = { workspace = true, default-features = false }
sp-genesis-builder = { workspace = true, default-features = false }
#
pallet-authority-discovery = { workspace = true, default-features = false }
pallet-authorship = { workspace = true, default-features = false }
pallet-babe = { workspace = true, default-features = false }
pallet-beefy = { workspace = true, default-features = false }
pallet-beefy-mmr = { workspace = true, default-features = false }
pallet-election-provider-multi-phase = { workspace = true, default-features = false }
pallet-grandpa = { workspace = true, default-features = false }
pallet-im-online = { workspace = true, default-features = false }
pallet-indices = { workspace = true, default-features = false }
pallet-migrations = { workspace = true, default-features = false }
pallet-mmr = { workspace = true, default-features = false }
pallet-offences = { workspace = true, default-features = false }
pallet-preimage = { workspace = true, default-features = false }
pallet-revive = { workspace = true, default-features = false }
pallet-scheduler = { workspace = true, default-features = false }
pallet-session = { workspace = true, default-features = false }
pallet-session-benchmarking = { workspace = true, default-features = false, optional = true }
pallet-staking = { workspace = true, default-features = false }
pallet-staking-reward-curve = { workspace = true, default-features = false }
pallet-sudo = { workspace = true, default-features = false }
pallet-timestamp = { workspace = true, default-features = false }

frame-metadata-hash-extension = { workspace = true, default-features = false }
frame-executive = { workspace = true, default-features = false }
frame-election-provider-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }

# RPC
frame-system-rpc-runtime-api = { workspace = true, default-features = false }
pallet-group-rpc-runtime-api = { workspace = true, default-features = false }
pallet-protocol-fee-rpc-runtime-api = { workspace = true, default-features = false }
pallet-staking-runtime-api = { workspace = true, default-features = false }
node-rpc-runtime-api = { workspace = true, default-features = false }

# Used for runtime benchmarking
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-system-benchmarking = { workspace = true, default-features = false, optional = true }
hex-literal = { version = "0.3.1", default-features = false, optional = true }

[build-dependencies]
polymesh-build-tool = { workspace = true, default-features = false, optional = true }

[features]
default = ["std", "equalize"]
testing = []
disable_fees = ["polymesh-transaction-payment/disable_fees"]
equalize = []

ci-runtime = []

# Backends
u64_backend = ["polymesh-primitives/u64_backend"]

no_std = [
    "polymesh-primitives/no_std",
    "u64_backend",
    "pallet-confidential-assets/no_std",
    "polymesh-dart/no_std",
]

std = [
    "polymesh-build-tool/std",
    "frame-metadata-hash-extension/std",
    "frame-election-provider-support/std",
    "frame-executive/std",
    "frame-support/std",
    "frame-system/std",
    "frame-system-rpc-runtime-api/std",
    "node-rpc-runtime-api/std",
    "pallet-asset/std",
    "pallet-authority-discovery/std",
    "pallet-babe/std",
    "pallet-beefy/std",
    "pallet-beefy-mmr/std",
    "pallet-mmr/std",
    "pallet-balances/std",
    "pallet-committee/std",
    "pallet-compliance-manager/std",
    "pallet-confidential-assets/std",
    "pallet-corporate-actions/std",
    "pallet-grandpa/std",
    "pallet-group/std",
    "pallet-group-rpc-runtime-api/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-multisig/std",
    "pallet-nft/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-protocol-fee/std",
    "pallet-protocol-fee-rpc-runtime-api/std",
    "pallet-revive/std",
    "pallet-session/std",
    "pallet-settlement/std",
    "pallet-staking/std",
    "pallet-staking-runtime-api/std",
    "pallet-statistics/std",
    "pallet-sto/std",
    "pallet-sudo/std",
    "pallet-transaction-payment/std",
    "polymesh-transaction-payment/std",
    "pallet-utility/std",
    "pallet-validators/std",
    "pallet-precompiles/std",
    "polymesh-runtime-common/std",
    "polymesh-weights/std",
    "polymesh-dart/std",
    "serde/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-consensus-babe/std",
    "sp-consensus-grandpa/std",
    "sp-genesis-builder/std",
    "sp-session/std",
    "sp-transaction-pool/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "pallet-session-benchmarking/runtime-benchmarks",
    "frame-system-benchmarking/runtime-benchmarks",
    "frame-election-provider-support/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "hex-literal",
    "pallet-asset/runtime-benchmarks",
    "pallet-babe/runtime-benchmarks",
    "pallet-balances/runtime-benchmarks",
    "pallet-beefy-mmr/runtime-benchmarks",
    "pallet-mmr/runtime-benchmarks",
    "pallet-committee/runtime-benchmarks",
    "pallet-compliance-manager/runtime-benchmarks",
	"pallet-confidential-assets/runtime-benchmarks",
    "pallet-corporate-actions/runtime-benchmarks",
    "pallet-grandpa/runtime-benchmarks",
    "pallet-group/runtime-benchmarks",
    "pallet-im-online/runtime-benchmarks",
    "pallet-indices/runtime-benchmarks",
    "pallet-migrations/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-nft/runtime-benchmarks",
    "pallet-pips/runtime-benchmarks",
    "pallet-portfolio/runtime-benchmarks",
    "pallet-preimage/runtime-benchmarks",
    "pallet-protocol-fee/runtime-benchmarks",
    "pallet-relayer/runtime-benchmarks",
    "pallet-revive/runtime-benchmarks",
    "pallet-scheduler/runtime-benchmarks",
    "pallet-settlement/runtime-benchmarks",
    "pallet-staking/runtime-benchmarks",
    "pallet-statistics/runtime-benchmarks",
    "pallet-sto/runtime-benchmarks",
    "pallet-transaction-payment/runtime-benchmarks",
    "polymesh-transaction-payment/runtime-benchmarks",
    "pallet-treasury/runtime-benchmarks",
    "pallet-utility/runtime-benchmarks",
    "pallet-validators/runtime-benchmarks",
    "pallet-precompiles/runtime-benchmarks",
    "polymesh-runtime-common/runtime-benchmarks",
]
running-ci = [
    "pallet-statistics/running-ci",
    "pallet-pips/running-ci",
    "pallet-identity/running-ci",
]

# Enable the metadata hash generation.
#
# This is hidden behind a feature because it increases the compile time.
# The wasm binary needs to be compiled twice, once to fetch the metadata,
# generate the metadata hash and then a second time with the
# `RUNTIME_METADATA_HASH` environment variable set for the `CheckMetadataHash`
# extension.
metadata-hash = ["polymesh-build-tool?/metadata-hash"]

# A convenience feature for enabling things when doing a build
# for an on-chain release.
on-chain-release-build = ["metadata-hash"]
