[package]
name = "pallet-pips"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
polymesh-primitives-derive = { workspace = true, default-features = false }
polymesh-runtime-common = { workspace = true, default-features = false }

pallet-group = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-balances = { workspace = true, default-features = false }
pallet-base = { workspace = true, default-features = false }
pallet-permissions = { workspace = true, default-features = false }
pallet-treasury = { workspace = true, default-features = false }

# General
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }
log = "0.4.8"

# Substrate
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }

frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }

pallet-timestamp = { workspace = true, default-features = false }

# Benchmarking
frame-benchmarking = { workspace = true, default-features = false, optional = true }
rand = { version = "0.8.2", default-features = false, optional = true }
rand_chacha = { version = "0.3.0", default-features = false, optional = true }
pallet-committee = { workspace = true, default-features = false, optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
running-ci = []
try-runtime = ["frame-support/try-runtime"]
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-base/std",
    "pallet-balances/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-timestamp/std",
    "pallet-treasury/std",
    "polymesh-primitives/std",
    "polymesh-common-utilities/std",
    "polymesh-runtime-common/std",
    "serde/std",
    "serde_derive",
    "sp-api/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "rand",
    "rand_chacha",
    "pallet-committee",
]
