[package]
name = "pallet-multisig"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pallet-identity = { workspace = true, default-features = false}
pallet-permissions = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false}

# General
log = "0.4.8"
serde = { version = "1.0.104", default-features = false }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-version = { workspace = true, default-features = false }

frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-benchmarking = { workspace = true, default-features = false, optional = true }

pallet-timestamp = { workspace = true, default-features = false }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-core/std",
	"sp-runtime/std",
	"frame-benchmarking/std",
	"frame-system/std",
	"frame-support/std",
	"polymesh-primitives/std",
	"pallet-identity/std",
]
runtime-benchmarks = [
	"frame-benchmarking",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks",
    "pallet-permissions/runtime-benchmarks",
    "polymesh-primitives/runtime-benchmarks",
]
try-runtime = []
