[package]
name = "polymesh-ink"
version = "5.0.0"
authors = ["Polymesh Association"]
edition = "2021"

[dependencies]
ink_primitives = { version = "3.0", default-features = false }
ink_metadata = { version = "3.0", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0", default-features = false }
ink_storage = { version = "3.0", default-features = false }
ink_lang = { version = "3.0", default-features = false }
ink_lang_codegen = { version = "3.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

polymesh-api = { version = "0.3.8", default-features = false, features = ["ink"] }

upgrade_tracker = { version = "1.0.0", path = "../upgrade_tracker/", default-features = false, features = ["ink-as-dependency"], optional = true }

[lib]
name = "polymesh_ink"
path = "src/lib.rs"
crate-type = [
  # Used for normal contract Wasm blobs for upgrades.
  "cdylib",
	# Used when contracts link to this crate.
	"rlib",
]

[features]
default = ["std"]

# Compile as upgradable library.
as-library = []

# Enable support for an "Upgrade tracker" contract.
tracker = [
	"upgrade_tracker",
]

std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
    "polymesh-api/std",
    "upgrade_tracker?/std",
]
ink-as-dependency = []
