// This file is part of the Polymesh distribution (https://github.com/PolymeshAssociation/Polymesh).
// Copyright (c) 2023 Polymesh

//! Autogenerated weights for pallet_confidential_assets
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-04-22, STEPS: `10`, REPEAT: 3, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `trance`, CPU: `AMD Ryzen 9 9950X3D 16-Core Processor`

// Executed Command:
// target/release/polymesh
// benchmark
// pallet
// --min-duration=1
// -s
// 10
// -r
// 3
// -p=pallet_confidential_assets
// -e=*
// --db-cache
// 512
// --heap-pages
// 4096
// --execution
// wasm
// --wasm-execution
// compiled
// --output
// ./
// --template
// .maintain/crate-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_primitives::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_confidential_assets using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl crate::WeightInfo for SubstrateWeight {
    // Storage: `ConfidentialAssets::LastCommittedAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::LastCommittedAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:0)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeCurrentRoot` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountCurveTreeCurrentRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:65 w:0)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountInnerNodes` (r:1 w:7)
    // Proof: `ConfidentialAssets::AccountInnerNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeLastUpdate` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountCurveTreeLastUpdate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// The range of component `l` is `[0, 65]`.
    fn update_account_curve_tree_root(l: u32) -> Weight {
        // Minimum execution time: 3_186 nanoseconds.
        Weight::from_parts(462_494_749, 0)
            // Standard Error: 1_898_302
            .saturating_add(Weight::from_parts(79_839_104, 0).saturating_mul(l.into()))
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(l.into())))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: `ConfidentialAssets::LastCommittedFeeAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::LastCommittedFeeAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextFeeAccountLeafIndex` (r:1 w:0)
    // Proof: `ConfidentialAssets::NextFeeAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountCurveTreeCurrentRoot` (r:1 w:1)
    // Proof: `ConfidentialAssets::FeeAccountCurveTreeCurrentRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountLeaves` (r:65 w:0)
    // Proof: `ConfidentialAssets::FeeAccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountInnerNodes` (r:1 w:7)
    // Proof: `ConfidentialAssets::FeeAccountInnerNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountCurveTreeRoots` (r:0 w:1)
    // Proof: `ConfidentialAssets::FeeAccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountCurveTreeLastUpdate` (r:0 w:1)
    // Proof: `ConfidentialAssets::FeeAccountCurveTreeLastUpdate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// The range of component `l` is `[0, 65]`.
    fn update_fee_account_curve_tree_root(l: u32) -> Weight {
        // Minimum execution time: 3_607 nanoseconds.
        Weight::from_parts(437_151_534, 0)
            // Standard Error: 1_498_862
            .saturating_add(Weight::from_parts(79_261_621, 0).saturating_mul(l.into()))
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(l.into())))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::AccountDid` (r:100 w:100)
    // Proof: `ConfidentialAssets::AccountDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::EncryptionKeyDid` (r:100 w:100)
    // Proof: `ConfidentialAssets::EncryptionKeyDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountEncryptionKey` (r:0 w:100)
    // Proof: `ConfidentialAssets::AccountEncryptionKey` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::EncryptionKeyAccount` (r:0 w:100)
    // Proof: `ConfidentialAssets::EncryptionKeyAccount` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::DidAccounts` (r:0 w:100)
    // Proof: `ConfidentialAssets::DidAccounts` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `k` is `[0, 100]`.
    fn register_accounts(k: u32) -> Weight {
        // Minimum execution time: 198_047 nanoseconds.
        Weight::from_parts(328_305_101, 0)
            // Standard Error: 600_751
            .saturating_add(Weight::from_parts(33_476_952, 0).saturating_mul(k.into()))
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(k.into())))
            .saturating_add(DbWeight::get().writes((5_u64).saturating_mul(k.into())))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::EncryptionKeyDid` (r:100 w:100)
    // Proof: `ConfidentialAssets::EncryptionKeyDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// The range of component `k` is `[0, 100]`.
    fn register_encryption_keys(k: u32) -> Weight {
        // Minimum execution time: 109_258 nanoseconds.
        Weight::from_parts(235_561_090, 0)
            // Standard Error: 649_263
            .saturating_add(Weight::from_parts(15_057_169, 0).saturating_mul(k.into()))
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(k.into())))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(k.into())))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `System::Account` (r:2 w:2)
    // Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::FeeAccountDid` (r:10 w:10)
    // Proof: `ConfidentialAssets::FeeAccountDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextFeeAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextFeeAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountLeaves` (r:0 w:10)
    // Proof: `ConfidentialAssets::FeeAccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `p` is `[0, 10]`.
    fn register_fee_accounts(p: u32) -> Weight {
        // Minimum execution time: 28_655 nanoseconds.
        Weight::from_parts(194_363_596, 0)
            // Standard Error: 2_525_572
            .saturating_add(Weight::from_parts(49_695_976, 0).saturating_mul(p.into()))
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(p.into())))
            .saturating_add(DbWeight::get().writes(2))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(p.into())))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::AccountDid` (r:2 w:0)
    // Proof: `ConfidentialAssets::AccountDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAssetId` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAssetId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AssetLeaves` (r:1 w:1)
    // Proof: `ConfidentialAssets::AssetLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CounterForAssetLeaves` (r:1 w:1)
    // Proof: `ConfidentialAssets::CounterForAssetLeaves` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::AssetCurveTreeCurrentRoot` (r:1 w:1)
    // Proof: `ConfidentialAssets::AssetCurveTreeCurrentRoot` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AssetInnerNodes` (r:0 w:4)
    // Proof: `ConfidentialAssets::AssetInnerNodes` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Details` (r:0 w:1)
    // Proof: `ConfidentialAssets::Details` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AssetCurveTreeLastUpdate` (r:0 w:1)
    // Proof: `ConfidentialAssets::AssetCurveTreeLastUpdate` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Decimals` (r:0 w:1)
    // Proof: `ConfidentialAssets::Decimals` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::OwnerAssets` (r:0 w:1)
    // Proof: `ConfidentialAssets::OwnerAssets` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Names` (r:0 w:1)
    // Proof: `ConfidentialAssets::Names` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Keys` (r:0 w:1)
    // Proof: `ConfidentialAssets::Keys` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AssetCurveTreeRoots` (r:0 w:1)
    // Proof: `ConfidentialAssets::AssetCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Symbols` (r:0 w:1)
    // Proof: `ConfidentialAssets::Symbols` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn create_asset() -> Weight {
        // Minimum execution time: 734_349 nanoseconds.
        Weight::from_parts(804_934_000, 0)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(16))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::AccountDid` (r:50 w:0)
    // Proof: `ConfidentialAssets::AccountDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Details` (r:50 w:0)
    // Proof: `ConfidentialAssets::Details` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountAssetRegistrations` (r:50 w:50)
    // Proof: `ConfidentialAssets::AccountAssetRegistrations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:50)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `p` is `[0, 50]`.
    fn register_account_assets(p: u32) -> Weight {
        // Minimum execution time: 19_718 nanoseconds.
        Weight::from_parts(1_476_269_380, 0)
            // Standard Error: 15_902_771
            .saturating_add(Weight::from_parts(428_218_027, 0).saturating_mul(p.into()))
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().reads((3_u64).saturating_mul(p.into())))
            .saturating_add(DbWeight::get().writes(1))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(p.into())))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::AccountDid` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::Details` (r:1 w:1)
    // Proof: `ConfidentialAssets::Details` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn mint_asset() -> Weight {
        // Minimum execution time: 5_442_783 nanoseconds.
        Weight::from_parts(5_704_092_000, 0)
            .saturating_add(DbWeight::get().reads(7))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: `Identity::KeyRecords` (r:1 w:0)
    // Proof: `Identity::KeyRecords` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    // Storage: `System::Account` (r:2 w:2)
    // Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::FeeAccountDid` (r:10 w:0)
    // Proof: `ConfidentialAssets::FeeAccountDid` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountStateCommitmentNullifiers` (r:10 w:10)
    // Proof: `ConfidentialAssets::FeeAccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::FeeAccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextFeeAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextFeeAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountLeaves` (r:0 w:10)
    // Proof: `ConfidentialAssets::FeeAccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `p` is `[0, 10]`.
    fn topup_fee_accounts(p: u32) -> Weight {
        // Minimum execution time: 60_936 nanoseconds.
        Weight::from_parts(3_247_947_589, 0)
            // Standard Error: 88_595_339
            .saturating_add(Weight::from_parts(749_397_973, 0).saturating_mul(p.into()))
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(p.into())))
            .saturating_add(DbWeight::get().writes(2))
            .saturating_add(DbWeight::get().writes((2_u64).saturating_mul(p.into())))
    }
    // Storage: `ConfidentialAssets::FeeAccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::FeeAccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::FeeAccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::FeeAccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextFeeAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextFeeAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `System::Account` (r:2 w:2)
    // Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    // Storage: `ConfidentialAssets::FeeAccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::FeeAccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn verify_fee_payment() -> Weight {
        // Minimum execution time: 5_594_633 nanoseconds.
        Weight::from_parts(6_578_879_000, 0)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(5))
    }
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AssetCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AssetCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:0 w:64)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:0 w:16)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingAffirmations` (r:0 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingAffirmations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementMemo` (r:0 w:1)
    // Proof: `ConfidentialAssets::SettlementMemo` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegCount` (r:0 w:1)
    // Proof: `ConfidentialAssets::SettlementLegCount` (`max_values`: None, `max_size`: None, mode: `Measured`)
    /// The range of component `l` is `[0, 16]`.
    fn create_settlement(l: u32) -> Weight {
        // Minimum execution time: 63_331 nanoseconds.
        Weight::from_parts(4_265_059_632, 0)
            // Standard Error: 76_684_234
            .saturating_add(Weight::from_parts(1_870_983_228, 0).saturating_mul(l.into()))
            .saturating_add(DbWeight::get().reads(3))
            .saturating_add(DbWeight::get().writes(4))
            .saturating_add(DbWeight::get().writes((5_u64).saturating_mul(l.into())))
    }
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingAffirmations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingAffirmations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn sender_affirmation() -> Weight {
        // Minimum execution time: 5_327_704 nanoseconds.
        Weight::from_parts(5_791_468_000, 0)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingAffirmations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingAffirmations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn receiver_affirmation() -> Weight {
        // Minimum execution time: 4_300_206 nanoseconds.
        Weight::from_parts(4_736_989_000, 0)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: `ConfidentialAssets::SettlementPendingAffirmations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingAffirmations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn instant_sender_affirmation() -> Weight {
        // Minimum execution time: 6_203_474 nanoseconds.
        Weight::from_parts(6_370_893_000, 0)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: `ConfidentialAssets::SettlementPendingAffirmations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingAffirmations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn instant_receiver_affirmation() -> Weight {
        // Minimum execution time: 5_494_372 nanoseconds.
        Weight::from_parts(5_633_487_000, 0)
            .saturating_add(DbWeight::get().reads(9))
            .saturating_add(DbWeight::get().writes(6))
    }
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingAffirmations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingAffirmations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    fn mediator_affirmation() -> Weight {
        // Minimum execution time: 428_226 nanoseconds.
        Weight::from_parts(436_442_000, 0)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn receiver_claim() -> Weight {
        // Minimum execution time: 5_627_135 nanoseconds.
        Weight::from_parts(6_470_643_000, 0)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(5))
    }
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn sender_update_counter() -> Weight {
        // Minimum execution time: 5_361_318 nanoseconds.
        Weight::from_parts(5_385_865_000, 0)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(5))
    }
    // Storage: `ConfidentialAssets::AccountStateCommitmentNullifiers` (r:1 w:1)
    // Proof: `ConfidentialAssets::AccountStateCommitmentNullifiers` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountCurveTreeRoots` (r:1 w:0)
    // Proof: `ConfidentialAssets::AccountCurveTreeRoots` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementState` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementState` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::LegAffirmationStatus` (r:1 w:1)
    // Proof: `ConfidentialAssets::LegAffirmationStatus` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementPendingFinalizations` (r:1 w:1)
    // Proof: `ConfidentialAssets::SettlementPendingFinalizations` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::SettlementLegs` (r:1 w:0)
    // Proof: `ConfidentialAssets::SettlementLegs` (`max_values`: None, `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::CurrentWorkerSessionId` (r:1 w:0)
    // Proof: `ConfidentialAssets::CurrentWorkerSessionId` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::NextAccountLeafIndex` (r:1 w:1)
    // Proof: `ConfidentialAssets::NextAccountLeafIndex` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `ConfidentialAssets::AccountLeaves` (r:0 w:1)
    // Proof: `ConfidentialAssets::AccountLeaves` (`max_values`: None, `max_size`: None, mode: `Measured`)
    fn sender_revert() -> Weight {
        // Minimum execution time: 5_185_243 nanoseconds.
        Weight::from_parts(5_484_733_000, 0)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(5))
    }
}
