[package]
name = "delegate_calls"
version = "4.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
publish = false

[dependencies]
ink_primitives = { version = "=3.0", default-features = false }
ink_prelude = { version = "=3.0", default-features = false }
ink_metadata = { version = "=3.0", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "=3.0", default-features = false }
ink_storage = { version = "=3.0", default-features = false }
ink_lang = { version = "=3.0", default-features = false }
ink_lang_codegen = { version = "=3.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

[lib]
name = "delegate_calls"
path = "lib.rs"
crate-type = ["cdylib"]

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_lang/std",
    "scale/std",
    "scale-info/std",
]
ink-as-dependency = []
