[package]
name = "pallet-utility"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
# Out Pallets
pallet-permissions = { workspace = true, default-features = false }
polymesh-transaction-payment = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = [
	"derive",
] }
frame-benchmarking = { workspace = true, default-features = false, optional = true }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
	"frame-benchmarking?/std",
	"codec/std",
	"frame-support/std",
	"frame-system/std",
	"scale-info/std",
	"sp-core/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"polymesh-transaction-payment/std",
	"polymesh-primitives/std",
]

runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"polymesh-transaction-payment/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
