[package]
name = "polymesh-runtime-itn"
version = "0.1.0"
authors = ["Polymath Inc."]
edition = "2018"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Common
polymesh-common-utilities = { path = "../../common", default-features = false }
polymesh-extensions = { path = "../extensions", default-features = false }
polymesh-primitives = { path = "../../../primitives", default-features = false }
polymesh-runtime-common = { path = "../common", default-features = false}
polymesh-weights = { path = "../../weights", default-features = false }

# Our pallets
pallet-asset = { path = "../../asset", default-features = false }
pallet-balances = { path = "../../balances", default-features = false }
pallet-base = { path = "../../base", default-features = false }
pallet-bridge = { path = "../../bridge", default-features = false }
pallet-committee = { path = "../../committee", default-features = false }
pallet-compliance-manager = { path = "../../compliance-manager", default-features = false }
pallet-corporate-actions = { path = "../../corporate-actions", default-features = false }
pallet-external-agents = { path = "../../external-agents", default-features = false }
pallet-group = { path = "../../group", default-features = false }
pallet-group-rpc-runtime-api = { path = "../../group/rpc/runtime-api", default-features = false }
pallet-identity = { path = "../../identity", default-features = false }
pallet-multisig = { path = "../../multisig", default-features = false }
pallet-permissions = { path = "../../permissions", default-features = false }
pallet-pips = { path = "../../pips", default-features = false }
pallet-portfolio = { path = "../../portfolio", default-features = false }
pallet-protocol-fee = { path = "../../protocol-fee", default-features = false }
pallet-relayer = { path = "../../relayer", default-features = false }
pallet-settlement = { path = "../../settlement", default-features = false }
pallet-staking = { path = "../../staking", default-features = false }
pallet-statistics = { path = "../../statistics", default-features = false }
pallet-sto = { path = "../../sto", default-features = false }
pallet-sudo = { path = "../../sudo", default-features = false }
pallet-transaction-payment = { path = "../../transaction-payment", default-features = false }
pallet-treasury = { path = "../../treasury", default-features = false }
pallet-utility = { path = "../../utility", default-features = false }
#polymesh-contracts = { path = "../../contracts", default-features = false }

# RPC
node-rpc-runtime-api = { path = "../../../rpc/runtime-api", default-features = false }
pallet-staking-rpc-runtime-api = { package = "pallet-staking-rpc-runtime-api", path = "../../staking/rpc/runtime-api", default-features = false }
pallet-protocol-fee-rpc-runtime-api = { package = "pallet-protocol-fee-rpc-runtime-api", path = "../../protocol-fee/rpc/runtime-api", default-features = false }
#pallet-contracts-rpc-runtime-api = { version = "3.0.0", default-features = false }

# Others
lazy_static = { version = "1.4.0", default-features = false }
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true }
smallvec = "1.4.0"

# Substrate
codec = { package = "parity-scale-codec", version = "2.0.0", default-features = false, features = ["derive"] }
frame-support = { version = "3.0.0", default-features = false }
frame-system = { version = "3.0.0", default-features = false }
frame-system-rpc-runtime-api = { version = "3.0.0", default-features = false }
pallet-authority-discovery = { version = "3.0.0", default-features = false }
pallet-authorship = { version = "3.0.0", default-features = false }
pallet-babe = { version = "3.0.0", default-features = false }
#pallet-contracts = { version = "3.0.0", default-features = false }
#pallet-contracts-primitives = { version = "3.0.0", default-features = false}
pallet-executive = { package = "frame-executive", version = "3.0.0", default-features = false }
pallet-grandpa = { version = "3.0.0", default-features = false }
pallet-im-online = { version = "3.0.0", default-features = false }
pallet-indices = { version = "3.0.0", default-features = false }
pallet-offences = { version = "3.0.0", default-features = false }
pallet-randomness-collective-flip = { version = "3.0.0", default-features = false }
pallet-scheduler = { version = "3.0.0", default-features = false }
pallet-session = { version = "3.0.0", default-features = false }
pallet-staking-reward-curve = { version = "3.0.0", default-features = false }
pallet-timestamp = { version = "3.0.0", default-features = false }
sp-api = { version = "3.0.0", default-features = false }
sp-arithmetic = { version = "3.0.0", default-features = false }
sp-authority-discovery = { version = "3.0.0", default-features = false }
sp-block-builder = { version = "3.0.0", default-features = false }
sp-consensus-babe = { version = "0.9.0", default-features = false }
sp-core = { version = "3.0.0", default-features = false }
sp-inherents = { version = "3.0.0", default-features = false }
sp-io = { version = "3.0.0", default-features = false }
sp-offchain = { version = "3.0.0", default-features = false }
sp-runtime = { version = "3.0.0", default-features = false }
sp-session = { version = "3.0.0", default-features = false }
sp-staking = { version = "3.0.0", default-features = false }
sp-std = { version = "3.0.0", default-features = false }
sp-transaction-pool = { version = "3.0.0", default-features = false }
sp-version = { version = "3.0.0", default-features = false }

# Crypto
cryptography_core = { git = "https://github.com/PolymathNetwork/cryptography.git", default-features = false, branch = "b2.2.3-2" }

[build-dependencies]
polymesh-build-tool = { path = "../build_tool", default-features = false }

[features]
default = ["std", "equalize"]
equalize = []

# Backends
u64_backend = ["cryptography_core/u64_backend"]
avx2_backend = ["cryptography_core/avx2_backend"]

migration-dry-run = []
no_std = [
    "cryptography_core/no_std",
    "u64_backend",
]
std = [
    "avx2_backend",
    "codec/std",
    "frame-support/std",
    "frame-system-rpc-runtime-api/std",
    "frame-system/std",
    "node-rpc-runtime-api/std",
    "pallet-asset/std",
    "pallet-authority-discovery/std",
    "pallet-authorship/std",
    "pallet-babe/std",
    "pallet-balances/std",
    "pallet-bridge/std",
    "pallet-committee/std",
    "pallet-compliance-manager/std",
    #"pallet-contracts-primitives/std",
    #"pallet-contracts-rpc-runtime-api/std",
    #"pallet-contracts/std",
    "pallet-executive/std",
    "pallet-external-agents/std",
    "pallet-grandpa/std",
    "pallet-group-rpc-runtime-api/std",
    "pallet-group/std",
    "pallet-identity/std",
    "pallet-im-online/std",
    "pallet-indices/std",
    "pallet-multisig/std",
    "pallet-offences/std",
    "pallet-permissions/std",
    "pallet-pips/std",
    "pallet-portfolio/std",
    "pallet-protocol-fee-rpc-runtime-api/std",
    "pallet-protocol-fee/std",
    "pallet-relayer/std",
    "pallet-randomness-collective-flip/std",
    "pallet-scheduler/std",
    "pallet-session/std",
    "pallet-settlement/std",
    "pallet-staking-rpc-runtime-api/std",
    "pallet-staking/std",
    "pallet-statistics/std",
    "pallet-sto/std",
    "pallet-sudo/std",
    "pallet-timestamp/std",
    "pallet-transaction-payment/std",
    "pallet-treasury/std",
    "pallet-utility/std",
    "polymesh-common-utilities/std",
    #"polymesh-contracts/std",
    "polymesh-primitives/std",
    "polymesh-runtime-common/std",
    "polymesh-weights/std",
    "serde/std",
    "sp-api/std",
    "sp-arithmetic/std",
    "sp-authority-discovery/std",
    "sp-block-builder/std",
    "sp-consensus-babe/std",
    "sp-core/std",
    "sp-inherents/std",
    "sp-io/std",
    "sp-offchain/std",
    "sp-runtime/std",
    "sp-session/std",
    "sp-staking/std",
    "sp-std/std",
    "sp-transaction-pool/std",
    "sp-version/std",
]
