ARG golangbase=1.24
FROM golang:${golangbase} as gobuild

ADD .docker/src/health-check/ /opt/health-check/
ADD .docker/src/rotate-keys/ /opt/rotate-keys/

WORKDIR /opt/health-check
RUN ls -a && \
    go build && \
    chmod 0755 /opt/health-check/polymesh-health-check

WORKDIR /opt/rotate-keys
RUN ls -a && \
    go build && \
    chmod 0755 /opt/rotate-keys/polymesh-rotate-keys

FROM debian:stable-slim

# install tools and dependencies
RUN DEBIAN_FRONTEND=noninteractive apt-get update && \
       apt-get upgrade -y && \
       apt-get install -y --no-install-recommends ca-certificates && \
       apt-get autoremove -y && \
       apt-get clean && \
       find /var/lib/apt/lists/ -type f -not -name lock -delete

COPY --chown=4002:4002 --from=gobuild      /opt/health-check/polymesh-health-check /usr/local/bin/check
COPY --chown=4002:4002 --from=gobuild      /opt/rotate-keys/polymesh-rotate-keys   /usr/local/bin/rotate
COPY --chown=4001:4001 ./polymesh-arm64 /usr/local/bin/polymesh

RUN mkdir /var/lib/polymesh && \
    chown 4001:4001 /var/lib/polymesh

USER 4001:4001

ENTRYPOINT ["/usr/local/bin/polymesh"]
CMD [ "-d", "/var/lib/polymesh" ]

HEALTHCHECK \
    --interval=10s \
    --start-period=120s \
    --timeout=5s \
    --retries=6 \
    CMD /usr/local/bin/check liveness
