[package]
name = "pallet-relayer"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
pallet-identity = { workspace = true, default-features = false}
polymesh-primitives = { workspace = true, default-features = false}

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
sp-runtime = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-std = { workspace = true, default-features = false }

# Only Benchmarking
frame-benchmarking = { workspace = true, default-features = false, optional = true }

[features]
default = ["std"]
no_std = []
std = [
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-std/std",
    "pallet-identity/std",
    "polymesh-primitives/std",
]
runtime-benchmarks = [
    "frame-benchmarking/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "polymesh-primitives/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
