[package]
name = "polymesh-worker-common"
version = "0.1.0"
authors = ["Polymesh Labs"]
license-file = "../../../LICENSE"
repository = "https://github.com/PolymeshAssociation/Polymesh"
description = "Polymesh worker common types"
edition = "2024"

[dependencies]
log = { version = "0.4", default-features = false }

codec = { workspace = true, default-features = false, features = ["derive"] }
ark-std = { workspace = true, default-features = false }

polkavm-derive = { version = "0.32.0", optional = true }

[features]
default = ["std", "testing"]

host_logger = []

# For the host-side.
impl_host_logger = ["host_logger"]

polkavm = ["polkavm-derive"]

testing = []

std = [
	"codec/std",
	"ark-std/std",
	"log/std",
]
