[package]
name = "pallet-portfolio"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
# Common
polymesh-primitives = { workspace = true, default-features = false }

# Our Pallets
pallet-base = { workspace = true, default-features = false  }
pallet-identity = { workspace = true, default-features = false  }
pallet-permissions = { workspace = true, default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }
log = "0.4.8"

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-runtime = { workspace = true, default-features = false }
sp-arithmetic = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }

# Only in STD
frame-benchmarking = { workspace = true, default-features = false, optional = true }

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-base/std",
    "pallet-identity/std",
    "pallet-permissions/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-std/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "pallet-identity/runtime-benchmarks",
    "pallet-permissions/runtime-benchmarks",
]
try-runtime = ["frame-support/try-runtime"]
