[package]
name = "pallet-validators"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
polymesh-primitives = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }

# Substrate staking
pallet-staking = { workspace = true, default-features = false }

# General
static_assertions = "1.1.0"
serde = { version = "1.0.104", default-features = false, features = ["alloc", "derive"] }
log = "0.4.8"

# Substrate
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false}
sp-runtime = { workspace = true, default-features = false }
sp-arithmetic = { workspace = true, default-features = false }
sp-staking = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
frame-election-provider-support = { workspace = true, default-features = false }
sp-npos-elections = { workspace = true, default-features = false}

pallet-session = { features = ["historical"], workspace = true, default-features = false }
pallet-authorship = { workspace = true, default-features = false }
pallet-babe = { workspace = true, default-features = false }

# Optional imports for benchmarking
frame-benchmarking = { workspace = true, default-features = false, optional = true }
rand_chacha = { version = "0.2", default-features = false, optional = true }

[dev-dependencies]
pallet-staking-reward-curve = { workspace = true, default-features = false }
sp-tracing = { workspace = true }

[features]
default = ["std"]
no_std = []
std = [
  "frame-benchmarking?/std",
	"polymesh-primitives/std",
	"serde/std",
	"codec/std",
	"sp-std/std",
	"sp-npos-elections/std",
	"sp-io/std",
	"frame-support/std",
	"frame-election-provider-support/std",
	"sp-runtime/std",
	"sp-staking/std",
	"pallet-session/std",
	"frame-system/std",
	"pallet-authorship/std",
	"pallet-identity/std",
	"pallet-staking/std",
	"pallet-babe/std",
	"sp-arithmetic/std",
	"rand_chacha",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
  "frame-election-provider-support/runtime-benchmarks",
	"rand_chacha",
  "sp-staking/runtime-benchmarks",
	"polymesh-primitives/runtime-benchmarks",
  "pallet-identity/runtime-benchmarks",
]
try-runtime = []
