[package]
name = "polymesh-runtime-common"
version = "1.0.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }

pallet-balances = { workspace = true, default-features = false  }
pallet-committee = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false  }
pallet-multisig = { workspace = true, default-features = false }
pallet-relayer = { workspace = true, default-features = false }

# RPC
pallet-group-rpc-runtime-api = { workspace = true, default-features = false}

# General
smallvec = "1.4.0"
log = "0.4.8"

# Substrate
codec = { package = "parity-scale-codec", version = "3.6.1", default-features = false, features = ["derive"] }
frame-election-provider-support = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-authorship = { workspace = true, default-features = false }
pallet-election-provider-multi-phase = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }

[features]
equalize = []
only-staking = []
default = ["std", "equalize"]
testing = []
no_std = []
std = [
    "frame-support/std",
    "frame-system/std",
    "pallet-authorship/std",
    "pallet-balances/std",
    "pallet-group-rpc-runtime-api/std",
    "pallet-identity/std",
    "pallet-multisig/std",
    "polymesh-primitives/std",
    "polymesh-common-utilities/std",
    "sp-runtime/std",
    "sp-std/std",
    "frame-election-provider-support/std",
    "pallet-election-provider-multi-phase/std",
    "sp-io/std"
]
runtime-benchmarks = [
    "pallet-balances/runtime-benchmarks",
    "pallet-committee/runtime-benchmarks",
    "pallet-identity/runtime-benchmarks",
    "pallet-multisig/runtime-benchmarks",
    "pallet-relayer/runtime-benchmarks",
    "polymesh-primitives/runtime-benchmarks",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
    "sp-runtime/runtime-benchmarks",
    "frame-election-provider-support/runtime-benchmarks",
    "pallet-election-provider-multi-phase/runtime-benchmarks",
]
