ARG rustbase=1.74.0
FROM rust:${rustbase}-bullseye

ARG toolchainversion=nightly-2023-12-01
ENV TOOLCHAIN="${toolchainversion}"

RUN apt update && \
  DEBIAN_FRONTEND=noninteractive apt install \
  build-essential \
  ca-certificates \
  clang \
  cmake \
  gcc \
  jq \
  libclang-dev \
  libssl-dev \
  pkg-config \
  rsync \
  protobuf-compiler \
  -y --no-install-recommends && \
  apt autoremove -y && \
  apt clean
RUN rustup toolchain install $TOOLCHAIN && \
  rustup default $TOOLCHAIN && \
  cargo install rustfilt cargo-binutils && \
  rustup component add rustfmt clippy llvm-tools-preview && \
  rustup target add wasm32-unknown-unknown && \
  cargo install cargo-outdated && \
  cargo install sccache cargo-sonar cargo-audit cargo-deny cargo-outdated cargo-nextest --locked
