[package]
name = "pallet-statistics"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
polymesh-primitives = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }

# Other
log = "0.4.8"
serde = { version = "1.0.112", default-features = false }
serde_derive = { version = "1.0.112", optional = true, default-features = false}

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-api = { workspace = true, default-features = false }
sp-arithmetic = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }

pallet-timestamp = { workspace = true, default-features = false }

# Only in Benchmarks
frame-benchmarking = { workspace = true, default-features = false, optional = true }

[dev-dependencies]
lazy_static = "1.4.0"

[features]
equalize = []
default = ["std", "equalize"]
no_std = []
only-staking = []
running-ci = []
std = [
	"serde_derive",
	"codec/std",
	"serde/std",
	"sp-core/std",
	"sp-std/std",
	"sp-io/std",
	"sp-api/std",
	"sp-arithmetic/std",
	"sp-runtime/std",
	"frame-support/std",
	"frame-system/std",
	"pallet-timestamp/std",
	"polymesh-primitives/std",
	"pallet-identity/std",
	"pallet-external-agents/std",
]
runtime-benchmarks = [
	"frame-benchmarking/runtime-benchmarks",
	"frame-benchmarking/std",
    "frame-support/runtime-benchmarks",
    "frame-system/runtime-benchmarks",
	"pallet-external-agents/runtime-benchmarks",
	"pallet-identity/runtime-benchmarks"
]
try-runtime = ["frame-support/try-runtime"]
