[package]
name = "polymesh-node-rpc"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"
license = "Apache-2.0"
repository = "https://github.com/PolymeshAssociation/substrate"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpsee = { version = "0.24.8", features = ["server"] }

polymesh-primitives = { workspace = true, default-features = false }
pallet-group-rpc = { workspace = true, default-features = false }
pallet-protocol-fee-rpc = {  workspace = true, default-features = false }
node-rpc = { workspace = true, default-features = false }

mmr-gadget = { workspace = true }
mmr-rpc = { workspace = true }

sc-chain-spec = { workspace = true }
sc-client-api = { workspace = true }
sc-consensus-babe = { workspace = true }
sc-consensus-babe-rpc = { workspace = true }
sc-consensus-beefy = { workspace = true }
sc-consensus-beefy-rpc = { workspace = true }
sc-consensus-grandpa = { workspace = true }
sc-consensus-grandpa-rpc = { workspace = true }
sc-rpc = { workspace = true }
sc-rpc-api = { workspace = true }
sc-rpc-spec-v2 = { workspace = true }
sc-sync-state-rpc = { workspace = true }
sc-transaction-pool-api = { workspace = true }
sp-api = { workspace = true, default-features = false }
sp-application-crypto = { workspace = true, default-features = false }
sp-block-builder = { workspace = true, default-features = false }
sp-blockchain = { workspace = true, default-features = false }
sp-consensus = { workspace = true, default-features = false }
sp-consensus-babe = { workspace = true, default-features = false }
sp-consensus-beefy = { workspace = true }
sp-keystore = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
substrate-frame-rpc-system = { workspace = true, default-features = false }

[features]
default = ["std"]
std = [
    "polymesh-primitives/std",
    "pallet-group-rpc/std",
    "pallet-protocol-fee-rpc/std",
    "node-rpc/std",
    "sp-api/std",
    "sp-block-builder/std",
    "sp-consensus-babe/std",
    "sp-keystore/std",
    "sp-runtime/std",
]
