[package]
name = "polymesh-dart-host-functions"
version = "0.1.0"
authors = ["Polymesh Labs"]
license-file = "../../../LICENSE"
repository = "https://github.com/PolymeshAssociation/Polymesh"
description = "Polymesh DART Confidential Assets host functions"
edition = "2024"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(substrate_runtime)'] }

[dependencies]
# Crypto
rand_core = { workspace = true, default-features = false }
rand_chacha = { workspace = true, default-features = false }
rand = { workspace = true, default-features = false, optional = true }

# Common
polymesh-primitives = { workspace = true, default-features = false }

# DART
polymesh-dart = { workspace = true, default-features = false, features = [
  "backend_bp", "sp-io"
] }
polymesh-dart-common = { workspace = true, default-features = false }
ark-ec = { workspace = true, default-features = false, features = ["substrate"] }
lazy_static = { version = "1.4.0", optional = true }
crossbeam = { version = "0.8", optional = true }
rayon = { version = "1.8", optional = true }
log = "0.4"

# Substrate
scale-info = { workspace = true, default-features = false, features = [
  "derive",
] }
codec = { workspace = true, default-features = false, features = ["derive"] }
sp-std = { workspace = true, default-features = false }
sp-core = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime-interface = { workspace = true, default-features = false }

[features]
default = ["std", "testing"]

testing = []

asm = ["polymesh-dart/asm"]
parallel = [
	"polymesh-dart/verifier_parallel",
	"polymesh-dart/parallel",
]

no_std = ["polymesh-dart/no_std"]
std = [
  "asm",
  "parallel",
  "rand/std",
  "rand_core/std",
  "rand_chacha/std",
  "rayon",
  "crossbeam",
  "lazy_static",
  "polymesh-dart/std",
  "ark-ec/std",
  "polymesh-primitives/std",
  "codec/std",
  "sp-std/std",
  "sp-core/std",
  "sp-io/std",
  "sp-runtime-interface/std",
]
runtime-benchmarks = ["testing"]
