[package]
name = "pallet-confidential-assets"
version = "0.1.0"
authors = ["Polymesh Labs"]
edition = "2021"

[dependencies]
# Common
polymesh-primitives = { workspace = true, default-features = false }
polymesh-runtime-common = { workspace = true, default-features = false }

# Our Pallets
pallet-identity = { workspace = true, default-features = false }
pallet-transaction-payment = { workspace = true, default-features = false }

# Crypto
polymesh-worker-extension = { workspace = true, default-features = false }
rand_core = { workspace = true, default-features = false, optional = true }
rand_chacha = { workspace = true, default-features = false, optional = true }

# DART
polymesh-dart = { workspace = true, default-features = false, features = [
  "backend_bp", "sp-io"
] }
polymesh-worker-protocol-dart-v1 = { workspace = true, default-features = false, features = ["runtime"] }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = [
  "derive",
] }
frame-system = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-io = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }

# Only Benchmarking
frame-benchmarking = { workspace = true, default-features = false, optional = true }

lazy_static = { version = "1.5.0", default-features = false, optional = true }
log = { version = "0.4", default-features = false }

[features]
equalize = []
default = ["std", "equalize"]

testing = ["polymesh-worker-extension/testing"]

asm = ["polymesh-dart/asm"]
parallel = ["polymesh-dart/parallel"]

no_std = ["polymesh-dart/no_std"]
std = [
  "asm",
  "parallel",
  "lazy_static",
  "codec/std",
  "polymesh-dart/std",
  "rand_core?/std",
  "rand_chacha?/std",
  "frame-support/std",
  "frame-system/std",
  "frame-benchmarking?/std",
  "pallet-identity/std",
  "pallet-transaction-payment/std",
  "polymesh-runtime-common/std",
  "polymesh-primitives/std",
  "polymesh-worker-extension/std",
	"polymesh-worker-protocol-dart-v1/std",
  "sp-runtime/std",
  "sp-std/std",
  "sp-io/std",
]
runtime-benchmarks = [
  "testing",
  "rand_core",
  "rand_chacha",
  "frame-benchmarking/runtime-benchmarks",
  "pallet-identity/runtime-benchmarks",
  "polymesh-primitives/runtime-benchmarks",
  "polymesh-worker-extension/runtime-benchmarks",
	"polymesh-worker-protocol-dart-v1/runtime-benchmarks",
  "sp-runtime/runtime-benchmarks",
]
try-runtime = []
