[package]
name = "asset-metadata"
version = "0.1.0"
edition = "2021"

[dependencies]
# Polymesh primitives.
polymesh-primitives = { path = "../", default-features = false }

# SCALE
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive", "decode"] }

[features]
default = ["std"]
no_std = []
std = [
	  "codec/std",
    "polymesh-primitives/std",
]
