[package]
name = "polymesh-build-tool"
version = "0.1.0"
authors = ["miguel <francisco.miguel.garcia.rodriguez@gmail.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
substrate-wasm-builder = { workspace = true, default-features = true, optional = true}

[features]
default = ["std"]
std = [ "substrate-wasm-builder" ]

# Enable the metadata hash generation.
#
# This is hidden behind a feature because it increases the compile time.
# The wasm binary needs to be compiled twice, once to fetch the metadata,
# generate the metadata hash and then a second time with the
# `RUNTIME_METADATA_HASH` environment variable set for the `CheckMetadataHash`
# extension.
metadata-hash = ["substrate-wasm-builder?/metadata-hash"]