[package]
name = "pallet-corporate-actions"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
# Common
polymesh-common-utilities = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }
polymesh-primitives-derive = { workspace = true, default-features = false }

# Our Pallets
pallet-base = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-asset = { workspace = true, default-features = false }
pallet-portfolio = { workspace = true, default-features = false }

# Other
serde = { version = "1.0.104", default-features = false }
serde_derive = { version = "1.0.104", optional = true, default-features = false }
log = "0.4"

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-arithmetic = { version = "6.0.0", default-features = false }
sp-core = { version = "7.0.0", default-features = false }
sp-std = { version = "5.0.0", default-features = false }
sp-io = { version = "7.0.0", default-features = false }
sp-runtime = { version = "7.0.0", default-features = false }
sp-version = { version = "5.0.0", default-features = false }
sp-api = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }
pallet-timestamp = { version = "4.0.0-dev", default-features = false }

pallet-compliance-manager = { workspace = true, default-features = false, optional = true }

[features]
default = ["std"]
no_std = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-asset/std",
    "pallet-base/std",
    "pallet-external-agents/std",
    "pallet-identity/std",
    "pallet-portfolio/std",
    "pallet-timestamp/std",
    "polymesh-primitives/std",
    "polymesh-common-utilities/std",
    "serde/std",
    "serde_derive",
    "sp-api/std",
    "sp-core/std",
    "sp-io/std",
    "sp-runtime/std",
    "sp-std/std",
    "sp-version/std",
    "sp-arithmetic/std",
]
runtime-benchmarks = [
    "frame-benchmarking",
    "pallet-compliance-manager"
]
try-runtime = ["frame-support/try-runtime"]
