#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
INTERFACES_DIR="${ROOT_DIR}/precompiles/src/interfaces"
SOLC_VERSION="0.8.33"

STUBS="
FungibleAssetStub.sol:FungibleAssetStub
PolymeshRuntime.sol:PolymeshRuntimeStub
"

build_runtime_bin() {
  sol="$1"
  contract="$2"
  out="$3"

  runtime_hex="$(
    solc --evm-version shanghai --optimize --optimize-runs 200 --bin-runtime "$sol" \
      | awk -v contract="$contract" '
        $0 ~ "^======= .*:" contract " =======$" { in_stub = 1; next }
        $0 ~ /^======= / { if (in_stub) exit; next }
        in_stub && $0 ~ /^Binary of the runtime part:/ { want_hex = 1; next }
        in_stub && want_hex && NF { print; exit }
      '
  )"
  if [ -z "$runtime_hex" ]; then
    echo "failed to produce runtime bytecode for $contract from $sol" >&2
    exit 1
  fi
  if ! printf '%s' "$runtime_hex" | grep -Eq '^[0-9a-fA-F]+$'; then
    echo "runtime bytecode extraction produced non-hex output" >&2
    exit 1
  fi

  if command -v xxd >/dev/null 2>&1; then
    printf '%s' "$runtime_hex" | xxd -r -p > "$out"
  elif command -v python3 >/dev/null 2>&1; then
    python3 - "$out" "$runtime_hex" <<'PY'
import binascii
import pathlib
import sys

out_path = sys.argv[1]
hex_data = sys.argv[2]
pathlib.Path(out_path).write_bytes(binascii.unhexlify(hex_data))
PY
  else
    echo "need either xxd or python3 to convert runtime hex to binary" >&2
    exit 1
  fi

  if [ ! -s "$out" ]; then
    echo "generated bytecode artifact is empty" >&2
    exit 1
  fi
}

current_solc_version="$(solc --version | awk '/^Version:/ { print $2 }' | cut -d+ -f1)"
if [ "$current_solc_version" != "$SOLC_VERSION" ]; then
  echo "expected solc ${SOLC_VERSION}, got ${current_solc_version}" >&2
  exit 1
fi

check_mode=false
if [ "${1:-}" = "--check" ]; then
  check_mode=true
fi

status=0
for entry in $STUBS; do
  sol_file="${entry%%:*}"
  contract="${entry#*:}"
  sol="${INTERFACES_DIR}/${sol_file}"
  bin="${INTERFACES_DIR}/${sol_file%.sol}.bin"

  if [ "$check_mode" = true ]; then
    if [ ! -s "$bin" ]; then
      echo "$(basename "$bin") is missing or empty. Run scripts/build_precompile_stub.sh" >&2
      status=1
      continue
    fi
    tmp_bin="$(mktemp)"
    build_runtime_bin "$sol" "$contract" "$tmp_bin"
    if cmp -s "$tmp_bin" "$bin"; then
      echo "$(basename "$bin") is up to date"
    else
      echo "$(basename "$bin") is stale. Run scripts/build_precompile_stub.sh" >&2
      status=1
    fi
    rm -f "$tmp_bin"
  else
    build_runtime_bin "$sol" "$contract" "$bin"
    echo "Wrote $bin"
  fi
done

exit "$status"
