#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
INTERFACES_DIR="${ROOT_DIR}/precompiles/src/interfaces"
SOLC_VERSION="0.8.33"

# Contract stubs to build. Each entry is a bare contract name; the sources and artifacts are
# "${INTERFACES_DIR}/<name>.sol" and "${INTERFACES_DIR}/<name>.bin".
STUBS="FungibleAssetStub NonFungibleAssetStub PolymeshRuntime"

# build_runtime_bin <contract-name> <output-path>
build_runtime_bin() {
  contract="$1"
  out_path="$2"
  sol="${INTERFACES_DIR}/${contract}.sol"

  if [ ! -f "$sol" ]; then
    echo "missing source $sol" >&2
    exit 1
  fi

  runtime_hex="$(
    solc --evm-version shanghai --optimize --optimize-runs 200 --bin-runtime "$sol" \
      | awk -v want="$contract" '
        $0 ~ /^======= / {
          if (in_stub) exit
          # Match the "======= <path>:<ContractName> =======" header for the wanted contract.
          split($0, parts, ":")
          name = parts[2]
          sub(/ =======$/, "", name)
          if (name == want) { in_stub = 1 }
          next
        }
        in_stub && $0 ~ /^Binary of the runtime part:/ { want_hex = 1; next }
        in_stub && want_hex && NF { print; exit }
      '
  )"
  if [ -z "$runtime_hex" ]; then
    echo "failed to produce runtime bytecode for $contract from $sol" >&2
    exit 1
  fi
  if ! printf '%s' "$runtime_hex" | grep -Eq '^[0-9a-fA-F]+$'; then
    echo "runtime bytecode extraction for $contract produced non-hex output" >&2
    exit 1
  fi

  if command -v xxd >/dev/null 2>&1; then
    printf '%s' "$runtime_hex" | xxd -r -p > "$out_path"
  elif command -v python3 >/dev/null 2>&1; then
    python3 - "$out_path" "$runtime_hex" <<'PY'
import binascii
import pathlib
import sys

out_path = sys.argv[1]
hex_data = sys.argv[2]
pathlib.Path(out_path).write_bytes(binascii.unhexlify(hex_data))
PY
  else
    echo "need either xxd or python3 to convert runtime hex to binary" >&2
    exit 1
  fi

  if [ ! -s "$out_path" ]; then
    echo "generated bytecode artifact for $contract is empty" >&2
    exit 1
  fi
}

current_solc_version="$(solc --version | awk '/^Version:/ { print $2 }' | cut -d+ -f1)"
if [ "$current_solc_version" != "$SOLC_VERSION" ]; then
  echo "expected solc ${SOLC_VERSION}, got ${current_solc_version}" >&2
  exit 1
fi

check_mode=false
if [ "${1:-}" = "--check" ]; then
  status=0
  tmp_bin="$(mktemp)"
  trap 'rm -f "$tmp_bin"' EXIT
  for contract in $STUBS; do
    bin="${INTERFACES_DIR}/${contract}.bin"
    if [ ! -s "$bin" ]; then
      echo "${contract}.bin is missing or empty. Run scripts/build_precompile_stub.sh" >&2
      status=1
      continue
    fi
    build_runtime_bin "$contract" "$tmp_bin"
    if cmp -s "$tmp_bin" "$bin"; then
      echo "${contract}.bin is up to date"
    else
      echo "${contract}.bin is stale. Run scripts/build_precompile_stub.sh" >&2
      status=1
    fi
  done
  exit "$status"
fi

for contract in $STUBS; do
  bin="${INTERFACES_DIR}/${contract}.bin"
  build_runtime_bin "$contract" "$bin"
  echo "Wrote $bin"
done
