#!/bin/sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname "$0")/.." && pwd)"
SOL="${ROOT_DIR}/precompiles/src/interfaces/FungibleAssetStub.sol"
BIN="${ROOT_DIR}/precompiles/src/interfaces/FungibleAssetStub.bin"
SOLC_VERSION="0.8.33"

build_runtime_bin() {
  runtime_hex="$(
    solc --evm-version shanghai --optimize --optimize-runs 200 --bin-runtime "$SOL" \
      | awk '
        $0 ~ /^======= .*:FungibleAssetStub =======$/ { in_stub = 1; next }
        $0 ~ /^======= / { if (in_stub) exit; next }
        in_stub && $0 ~ /^Binary of the runtime part:/ { want_hex = 1; next }
        in_stub && want_hex && NF { print; exit }
      '
  )"
  if [ -z "$runtime_hex" ]; then
    echo "failed to produce runtime bytecode from $SOL" >&2
    exit 1
  fi
  if ! printf '%s' "$runtime_hex" | grep -Eq '^[0-9a-fA-F]+$'; then
    echo "runtime bytecode extraction produced non-hex output" >&2
    exit 1
  fi
  printf '%s' "$runtime_hex" | xxd -r -p > "$1"
  if [ ! -s "$1" ]; then
    echo "generated bytecode artifact is empty" >&2
    exit 1
  fi
}

current_solc_version="$(solc --version | awk '/^Version:/ { print $2 }' | cut -d+ -f1)"
if [ "$current_solc_version" != "$SOLC_VERSION" ]; then
  echo "expected solc ${SOLC_VERSION}, got ${current_solc_version}" >&2
  exit 1
fi

if [ "${1:-}" = "--check" ]; then
  if [ ! -s "$BIN" ]; then
    echo "FungibleAssetStub.bin is missing or empty. Run scripts/build_precompile_stub.sh" >&2
    exit 1
  fi
  tmp_bin="$(mktemp)"
  trap 'rm -f "$tmp_bin"' EXIT
  build_runtime_bin "$tmp_bin"
  if cmp -s "$tmp_bin" "$BIN"; then
    echo "FungibleAssetStub.bin is up to date"
    exit 0
  fi
  echo "FungibleAssetStub.bin is stale. Run scripts/build_precompile_stub.sh" >&2
  exit 1
fi

build_runtime_bin "$BIN"
echo "Wrote $BIN"
