// Copyright 2019-2020 Parity Technologies (UK) Ltd.
// This file is part of Substrate.

// Substrate is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.

// Substrate is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.

// You should have received a copy of the GNU General Public License
// along with Substrate.  If not, see <http://www.gnu.org/licenses/>.

// # Modified by Polymesh Association - 23rd March 2020
// This module is inspired by the `membership` module of the substrate framework
// https://github.com/PolymeshAssociation/substrate/tree/a439a7aa5a9a3df2a42d9b25ea04288d3a0866e8/frame/membership
// It get customize as per the Polymesh requirements
// - Change member type from `AccountId` to `IdentityId`.
// - Remove `change_key` function from the implementation in the favour of "User can hold only single identity on Polymesh blockchain".
// - Remove the logic of prime member logic that led the removal of `set_prime()` & `clear_prime()` dispatchables.
// - Add `abdicate_membership()` dispatchable to allows a caller member to unilaterally quit without this
// being subject to a GC vote.

//! # Group Module
//!
//! The Group module is used to manage a set of identities. A group of identities can be a
//! collection of CDD providers, council members for governance and so on. This is an instantiable
//! module.
//!
//! ## Overview
//!
//! Allows control of membership of a set of `IdentityId`s, useful for managing group
//! membership. This includes:
//!
//! - adding a new identity,
//! - removing an identity from a group,
//! - swapping members,
//! - reseting group members.
//!
//! ## Active and Inactive members
//!
//! There are two kinds of members:
//!  - *Active members*, who can *act* on behalf of this group. For instance, any active CDD providers can
//!  generate CDD claims.
//!  - *Inactive members*, Members who were active previously but at some point they were disabled. Each
//!  inactive member has two timestamps:
//!     - `deactivated_at`: It indicates the moment when this member was disabled. Any claim generated *after*
//!     this moment is considered as invalid.
//!     - `expiry`: It is the moment when it should be removed completely from this group. From
//!     that moment on, any claim is considered invalid (as a group claim).
//!
//! This mechanism has been designed to disable any _compromised_ member at specific moment without
//! disabling all claims generated by this member. It means that, claims generated before disabling
//! any member are still valid and anyone generated after that moment will be invalid.
//!
//! ## Interface
//!
//! ### Dispatchable Functions
//!
//! - `add_member` - Adds a new identity to the group, as an *active* member..
//! - `remove_member` - Removes an *active* member from the group if it exists.
//! - `swap_member` - Replaces one identity with another.
//! - `reset_members` - Re-initializes group members.
//! - `abdicate_membership` - Unilateral abdication without being subject to a GC vote.
//!
//! ### Other Public Methods
//!
//! - `get_valid_members` - Returns the current "active members" and any "valid member" whose
//! revocation time-stamp is in the future.

// Ensure we're `no_std` when compiling for Wasm.
#![cfg_attr(not(feature = "std"), no_std)]

#[cfg(feature = "runtime-benchmarks")]
pub mod benchmarking;

use frame_support::{
    dispatch::DispatchResult,
    ensure,
    traits::{ChangeMembers, EnsureOrigin, InitializeMembers},
    weights::Weight,
};
use pallet_identity as identity;
use polymesh_primitives::{
    committee::COMMITTEE_MEMBERS_MAX,
    traits::group::{GroupTrait, InactiveMember, MemberCount},
    IdentityId, GC_DID,
};
use sp_std::{prelude::*, vec::Vec};

pub use pallet::*;

#[frame_support::pallet]
pub mod pallet {
    use super::*;
    use frame_support::pallet_prelude::*;
    use frame_system::pallet_prelude::*;

    type Identity<T> = identity::Pallet<T>;
    pub trait WeightInfo {
        fn set_active_members_limit() -> Weight;
        fn add_member() -> Weight;
        fn remove_member() -> Weight;
        fn disable_member() -> Weight;
        fn swap_member() -> Weight;
        fn reset_members(new_members_len: u32) -> Weight;
        fn abdicate_membership() -> Weight;
    }

    #[pallet::config]
    pub trait Config<I: 'static = ()>:
        frame_system::Config
        + pallet_permissions::Config
        + pallet_timestamp::Config
        + pallet_identity::Config
    {
        /// Required origin for changing the active limit.
        /// It's recommended that e.g., in case of a committee,
        /// this be an origin that cannot be formed through a committee majority.
        type LimitOrigin: EnsureOrigin<<Self as frame_system::Config>::RuntimeOrigin>;

        /// Required origin for adding a member (though can always be Root).
        type AddOrigin: EnsureOrigin<<Self as frame_system::Config>::RuntimeOrigin>;

        /// Required origin for removing a member (though can always be Root).
        type RemoveOrigin: EnsureOrigin<<Self as frame_system::Config>::RuntimeOrigin>;

        /// Required origin for adding and removing a member in a single action.
        type SwapOrigin: EnsureOrigin<<Self as frame_system::Config>::RuntimeOrigin>;

        /// Required origin for resetting membership.
        type ResetOrigin: EnsureOrigin<<Self as frame_system::Config>::RuntimeOrigin>;

        /// The receiver of the signal for when the membership has been initialized. This happens pre-
        /// genesis and will usually be the same as `MembershipChanged`. If you need to do something
        /// different on initialization, then you can change this accordingly.
        type MembershipInitialized: InitializeMembers<IdentityId>;

        /// The receiver of the signal for when the membership has changed.
        type MembershipChanged: ChangeMembers<IdentityId>;

        /// Weight information for extrinsics in this pallet.
        type WeightInfo: WeightInfo;
    }

    #[pallet::event]
    #[pallet::generate_deposit(pub(super) fn deposit_event)]
    pub enum Event<T: Config<I>, I: 'static = ()> {
        /// The given member was added; see the transaction for who.
        /// caller DID, New member DID.
        MemberAdded(IdentityId, IdentityId),
        /// The given member was removed; see the transaction for who.
        /// caller DID, member DID that get removed.
        MemberRemoved(IdentityId, IdentityId),
        /// The given member has been revoked at specific time-stamp.
        /// caller DID, member DID that get revoked.
        MemberRevoked(IdentityId, IdentityId),
        /// Two members were swapped; see the transaction for who.
        /// caller DID, Removed DID, New add DID.
        MembersSwapped(IdentityId, IdentityId, IdentityId),
        /// The membership was reset; see the transaction for who the new set is.
        /// caller DID, List of new members.
        MembersReset(IdentityId, Vec<IdentityId>),
        /// The limit of how many active members there can be concurrently was changed.
        ActiveLimitChanged(IdentityId, MemberCount, MemberCount),
    }

    const STORAGE_VERSION: StorageVersion = StorageVersion::new(1);

    #[pallet::pallet]
    #[pallet::storage_version(STORAGE_VERSION)]
    pub struct Pallet<T, I = ()>(PhantomData<(T, I)>);

    /// The current "active" membership, stored as an ordered Vec.
    #[pallet::storage]
    #[pallet::unbounded]
    #[pallet::getter(fn active_members)]
    pub type ActiveMembers<T: Config<I>, I: 'static = ()> =
        StorageValue<_, Vec<IdentityId>, ValueQuery>;

    /// The current "inactive" membership, stored as an ordered Vec.
    #[pallet::storage]
    #[pallet::unbounded]
    #[pallet::getter(fn inactive_members)]
    pub type InactiveMembers<T: Config<I>, I: 'static = ()> =
        StorageValue<_, Vec<InactiveMember<T::Moment>>, ValueQuery>;

    /// Limit of how many "active" members there can be.
    #[pallet::storage]
    pub type ActiveMembersLimit<T: Config<I>, I: 'static = ()> = StorageValue<_, u32, ValueQuery>;

    #[pallet::genesis_config]
    #[derive(frame_support::DefaultNoBound)]
    pub struct GenesisConfig<T: Config<I>, I: 'static = ()> {
        pub active_members_limit: u32,
        pub active_members: Vec<IdentityId>,
        #[serde(skip)]
        pub phantom: PhantomData<(T, I)>,
    }

    #[pallet::genesis_build]
    impl<T: Config<I>, I: 'static> BuildGenesisConfig for GenesisConfig<T, I> {
        fn build(&self) {
            use frame_support::traits::InitializeMembers;

            let mut members = self.active_members.clone();
            assert!(members.len() as MemberCount <= self.active_members_limit);
            members.sort();
            T::MembershipInitialized::initialize_members(&members);
            ActiveMembers::<T, I>::put(members);
            ActiveMembersLimit::<T, I>::put(self.active_members_limit);
        }
    }

    #[pallet::hooks]
    impl<T: Config<I>, I: 'static> Hooks<BlockNumberFor<T>> for Pallet<T, I> {
        fn on_initialize(_n: BlockNumberFor<T>) -> Weight {
            polymesh_primitives::migrate::frame_v2_instance_migrate::<Pallet<T, I>, I>(
                "Group",
                STORAGE_VERSION,
            )
        }
    }

    #[pallet::call]
    impl<T: Config<I>, I: 'static> Pallet<T, I> {
        /// Change this group's limit for how many concurrent active members they may be.
        ///
        /// # Arguments
        /// * `limit` - the number of active members there may be concurrently.
        #[pallet::weight(<T as Config<I>>::WeightInfo::set_active_members_limit())]
        #[pallet::call_index(0)]
        pub fn set_active_members_limit(
            origin: OriginFor<T>,
            limit: MemberCount,
        ) -> DispatchResult {
            T::LimitOrigin::ensure_origin(origin)?;
            ensure!(
                limit <= COMMITTEE_MEMBERS_MAX,
                Error::<T, I>::ActiveMembersLimitOverflow
            );
            let old = ActiveMembersLimit::<T, I>::mutate(|slot| core::mem::replace(slot, limit));
            Self::deposit_event(Event::ActiveLimitChanged(GC_DID, limit, old));
            Ok(())
        }

        /// Disables a member at specific moment.
        ///
        /// Please note that if member is already revoked (a "valid member"), its revocation
        /// time-stamp will be updated.
        ///
        /// Any disabled member should NOT allow to act like an active member of the group. For
        /// instance, a disabled CDD member should NOT be able to generate a CDD claim. However any
        /// generated claim issued before `at` would be considered as a valid one.
        ///
        /// If you want to invalidate any generated claim, you should use `Self::remove_member`.
        ///
        /// # Arguments
        /// * `at` - Revocation time-stamp.
        /// * `who` - Target member of the group.
        /// * `expiry` - Time-stamp when `who` is removed from CDD. As soon as it is expired, the
        /// generated claims will be "invalid" as `who` is not considered a member of the group.
        #[pallet::weight(<T as Config<I>>::WeightInfo::disable_member())]
        #[pallet::call_index(1)]
        pub fn disable_member(
            origin: OriginFor<T>,
            who: IdentityId,
            expiry: Option<T::Moment>,
            at: Option<T::Moment>,
        ) -> DispatchResult {
            T::RemoveOrigin::ensure_origin(origin)?;

            <Self as GroupTrait<T::Moment>>::disable_member(who, expiry, at)
        }

        /// Adds a member `who` to the group. May only be called from `AddOrigin` or root.
        ///
        /// # Arguments
        /// * `origin` - Origin representing `AddOrigin` or root
        /// * `who` - IdentityId to be added to the group.
        #[pallet::weight(<T as Config<I>>::WeightInfo::add_member())]
        #[pallet::call_index(2)]
        pub fn add_member(origin: OriginFor<T>, who: IdentityId) -> DispatchResult {
            T::AddOrigin::ensure_origin(origin)?;
            <Self as GroupTrait<T::Moment>>::add_member(who)
        }

        /// Removes a member `who` from the set. May only be called from `RemoveOrigin` or root.
        ///
        /// Any claim previously generated by this member is not valid as a group claim. For
        /// instance, if a CDD member group generated a claim for a target identity and then it is
        /// removed, that claim will be invalid.  In case you want to keep the validity of generated
        /// claims, you have to use `Self::disable_member` function
        ///
        /// # Arguments
        /// * `origin` - Origin representing `RemoveOrigin` or root
        /// * `who` - IdentityId to be removed from the group.
        #[pallet::weight(<T as Config<I>>::WeightInfo::remove_member())]
        #[pallet::call_index(3)]
        pub fn remove_member(origin: OriginFor<T>, who: IdentityId) -> DispatchResult {
            T::RemoveOrigin::ensure_origin(origin)?;
            Self::base_remove_member(who)
        }

        /// Swaps out one member `remove` for another member `add`.
        ///
        /// May only be called from `SwapOrigin` or root.
        ///
        /// # Arguments
        /// * `origin` - Origin representing `SwapOrigin` or root
        /// * `remove` - IdentityId to be removed from the group.
        /// * `add` - IdentityId to be added in place of `remove`.
        #[pallet::weight(<T as Config<I>>::WeightInfo::swap_member())]
        #[pallet::call_index(4)]
        pub fn swap_member(
            origin: OriginFor<T>,
            remove: IdentityId,
            add: IdentityId,
        ) -> DispatchResult {
            T::SwapOrigin::ensure_origin(origin)?;

            if remove == add {
                return Ok(());
            }

            let mut members = ActiveMembers::<T, I>::get();
            let remove_location = members
                .binary_search(&remove)
                .ok()
                .ok_or(Error::<T, I>::NoSuchMember)?;
            let _add_location = members
                .binary_search(&add)
                .err()
                .ok_or(Error::<T, I>::DuplicateMember)?;
            members[remove_location] = add;
            members.sort();
            ActiveMembers::<T, I>::put(&members);

            T::MembershipChanged::change_members_sorted(&[add], &[remove], &members[..]);
            let current_did = GC_DID;
            Self::deposit_event(Event::MembersSwapped(current_did, remove, add));
            Ok(())
        }

        /// Changes the membership to a new set, disregarding the existing membership.
        /// May only be called from `ResetOrigin` or root.
        ///
        /// # Arguments
        /// * `origin` - Origin representing `ResetOrigin` or root
        /// * `members` - New set of identities
        #[pallet::weight(<T as Config<I>>::WeightInfo::reset_members(members.len() as u32))]
        #[pallet::call_index(5)]
        pub fn reset_members(origin: OriginFor<T>, members: Vec<IdentityId>) -> DispatchResult {
            T::ResetOrigin::ensure_origin(origin)?;

            Self::ensure_within_active_members_limit(&members)?;

            let mut new_members = members.clone();
            new_members.sort();
            ActiveMembers::<T, I>::mutate(|m| {
                T::MembershipChanged::set_members_sorted(&new_members[..], m);
                *m = new_members;
            });
            let current_did = GC_DID;
            Self::deposit_event(Event::MembersReset(current_did, members));
            Ok(())
        }

        /// Allows the calling member to *unilaterally quit* without this being subject to a GC
        /// vote.
        ///
        /// # Arguments
        /// * `origin` - Member of committee who wants to quit.
        ///
        /// # Error
        ///
        /// * Only primary key can abdicate.
        /// * Last member of a group cannot abdicate.
        #[pallet::weight(<T as Config<I>>::WeightInfo::abdicate_membership())]
        #[pallet::call_index(6)]
        pub fn abdicate_membership(origin: OriginFor<T>) -> DispatchResult {
            let (who, remove_id) = Identity::<T>::ensure_did(origin)?;

            ensure!(
                <Identity<T>>::is_primary_key(&remove_id, &who),
                Error::<T, I>::OnlyPrimaryKeyAllowed
            );

            let mut members = Self::get_members();
            ensure!(members.len() > 1, Error::<T, I>::LastMemberCannotQuit);
            ensure!(
                members.binary_search(&remove_id).is_ok(),
                Error::<T, I>::NoSuchMember
            );

            members.retain(|id| *id != remove_id);
            ActiveMembers::<T, I>::put(&members);

            T::MembershipChanged::change_members_sorted(&[], &[remove_id], &members[..]);
            Ok(())
        }
    }

    #[pallet::error]
    pub enum Error<T, I = ()> {
        /// Only primary key of the identity is allowed.
        OnlyPrimaryKeyAllowed,
        /// Group member was added already.
        DuplicateMember,
        /// Can't remove a member that doesn't exist.
        NoSuchMember,
        /// Last member of the committee can not quit.
        LastMemberCannotQuit,
        /// The limit for the number of concurrent active members for this group has been exceeded.
        ActiveMembersLimitExceeded,
        /// Active member limit was greater than maximum committee members limit.
        ActiveMembersLimitOverflow,
    }
}

impl<T: Config<I>, I: 'static> Pallet<T, I> {
    /// Ensure that updating the active set to `members` will not exceed the set limit.
    fn ensure_within_active_members_limit(members: &[IdentityId]) -> DispatchResult {
        ensure!(
            members.len() as MemberCount <= ActiveMembersLimit::<T, I>::get(),
            Error::<T, I>::ActiveMembersLimitExceeded
        );
        Ok(())
    }

    /// Returns the current "active members" and any "valid member" whose revocation time-stamp is
    /// in the future.
    pub fn get_valid_members() -> Vec<IdentityId> {
        let now = <pallet_timestamp::Pallet<T>>::get();
        Self::get_valid_members_at(now)
    }

    /// Removes a member `who` as "active" or "inactive" member.
    ///
    /// # Arguments
    /// * `who` IdentityId to be removed from the group.
    fn base_remove_member(who: IdentityId) -> DispatchResult {
        Self::base_remove_active_member(who).or_else(|_| Self::base_remove_inactive_member(who))
    }

    /// Removes `who` as "inactive member"
    ///
    /// # Errors
    /// * `NoSuchMember` if `who` is not part of *inactive members*.
    fn base_remove_inactive_member(who: IdentityId) -> DispatchResult {
        let inactive_who = InactiveMember::<T::Moment>::from(who);
        let mut members = InactiveMembers::<T, I>::get();
        let position = members
            .binary_search(&inactive_who)
            .ok()
            .ok_or(Error::<T, I>::NoSuchMember)?;

        members.swap_remove(position);

        InactiveMembers::<T, I>::put(&members);
        let current_did = GC_DID;
        Self::deposit_event(Event::MemberRemoved(current_did, who));
        Ok(())
    }

    /// Removes `who` as "active member"
    ///
    /// # Errors
    /// * `NoSuchMember` if `who` is not part of *active members*.
    fn base_remove_active_member(who: IdentityId) -> DispatchResult {
        let mut members = ActiveMembers::<T, I>::get();
        let location = members
            .binary_search(&who)
            .ok()
            .ok_or(Error::<T, I>::NoSuchMember)?;

        members.remove(location);
        ActiveMembers::<T, I>::put(&members);

        T::MembershipChanged::change_members_sorted(&[], &[who], &members[..]);
        let current_did = GC_DID;
        Self::deposit_event(Event::MemberRemoved(current_did, who));
        Ok(())
    }
}

/// Retrieve all members of this group
/// Is the given `IdentityId` a valid member?
impl<T: Config<I>, I: 'static> GroupTrait<T::Moment> for Pallet<T, I> {
    /// Returns the "active members".
    #[inline]
    fn get_members() -> Vec<IdentityId> {
        ActiveMembers::<T, I>::get()
    }

    /// Returns inactive members who are not expired yet.
    #[inline]
    fn get_inactive_members() -> Vec<InactiveMember<T::Moment>> {
        let now = <pallet_timestamp::Pallet<T>>::get();
        InactiveMembers::<T, I>::get()
            .into_iter()
            .filter(|member| !Self::is_member_expired(member, now))
            .collect::<Vec<_>>()
    }

    /// Transforms an *active* membership into a *inactive* one.
    ///
    /// # Arguments
    /// * `who`: An *active* member.
    /// * `expiry`: When that *inactive* member will be completely removed from this group. If
    /// `None` that member will keep as *inactive* forever.
    /// * `at`: A past moment when `who` was considered as *inactive*. Any generated claim from
    /// that moment is considered as invalid. If `None`, the current block is used.
    fn disable_member(
        who: IdentityId,
        expiry: Option<T::Moment>,
        at: Option<T::Moment>,
    ) -> DispatchResult {
        Self::base_remove_active_member(who)?;
        let current_did = GC_DID;

        let deactivated_at = at.unwrap_or_else(<pallet_timestamp::Pallet<T>>::get);
        let inactive_member = InactiveMember {
            id: who,
            expiry,
            deactivated_at,
        };

        InactiveMembers::<T, I>::mutate(|members| {
            // Remove expired members.
            let now = <pallet_timestamp::Pallet<T>>::get();
            members.retain(|m| {
                if !Self::is_member_expired(m, now) {
                    true
                } else {
                    Self::deposit_event(Event::MemberRemoved(current_did, who));
                    false
                }
            });

            // Update inactive member
            if let Ok(idx) = members.binary_search(&inactive_member) {
                members[idx] = inactive_member;
            } else {
                members.push(inactive_member);
                members.sort();
            }
        });

        Self::deposit_event(Event::MemberRevoked(current_did, who));
        Ok(())
    }

    /// Adds a new member to the group
    fn add_member(who: IdentityId) -> DispatchResult {
        let mut members = ActiveMembers::<T, I>::get();
        let location = members
            .binary_search(&who)
            .err()
            .ok_or(Error::<T, I>::DuplicateMember)?;
        members.insert(location, who);
        Self::ensure_within_active_members_limit(&members)?;
        ActiveMembers::<T, I>::put(&members);

        T::MembershipChanged::change_members_sorted(&[who], &[], &members[..]);
        let current_did = GC_DID;
        Self::deposit_event(Event::MemberAdded(current_did, who));
        Ok(())
    }
}
