[package]
name = "pallet-nft"
version = "0.1.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
# Our crates
pallet-asset = { workspace = true, default-features = false  }
pallet-base = { workspace = true, default-features = false }
pallet-external-agents = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-portfolio = { workspace = true, default-features = false }
polymesh-primitives = { workspace = true, default-features = false }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
frame-support = { version = "4.0.0-dev", default-features = false }
frame-system = { version = "4.0.0-dev", default-features = false }
scale-info = { version = "2.0", default-features = false, features = ["derive"] }
sp-runtime = { version = "7.0.0", default-features = false }
sp-std = { version = "5.0.0", default-features = false }
# Other crates
log = "0.4.8"

# Only in STD
frame-benchmarking = { version = "4.0.0-dev", default-features = false, optional = true }

[features]
default = ["std"]
no_std = []
std = [
    "codec/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-asset/std",
    "pallet-external-agents/std",
    "pallet-identity/std",
    "pallet-portfolio/std",
    "polymesh-primitives/std",
    "sp-std/std"
]
runtime-benchmarks = [
    "frame-benchmarking",
]
try-runtime = ["frame-support/try-runtime"]
