[package]
name = "metadata-tools"
version = "0.1.0"
edition = "2021"

[dependencies]
substrate-differ = { git = "https://github.com/PolymeshAssociation/subwasm.git", branch = "polymesh", default-features = false, features = ["v14", "reduced"] }

frame-metadata = { version = "16.0", features = ["std", "legacy"] }

anyhow = "1.0"
clap = { version = "4.0", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3.0" }
env_logger = { version = "0.11.5", default-features = false }
hex = "0.4.3"
jsonrpsee = { version = "0.24.7", features = ["http-client","ws-client"] }
serde = "1.0.215"
serde_json = "1.0.133"
sp-version = { version = "35.0.0", default-features = false, features = ["std"] }
tokio = { version = "1.42.0", features = ["rt"] }

