[package]
name = "integration"
version = "0.1.0"
edition = "2021"

[patch.crates-io]
# Use these for testing new versions of `polymesh-api`.
#polymesh-api = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-client = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-client-extras = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-tester = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-codegen = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-codegen-macro = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
# local paths
#polymesh-api = { path = "../../polymesh-api/" }
#polymesh-api-client = { path = "../../polymesh-api/crates/polymesh-api-client/" }
#polymesh-api-client-extras = { path = "../../polymesh-api/crates/polymesh-api-client-extras/" }
#polymesh-api-tester = { path = "../../polymesh-api/crates/polymesh-api-tester/" }
#polymesh-api-codegen = { path = "../../polymesh-api/crates/polymesh-api-codegen/" }
#polymesh-api-codegen-macro = { path = "../../polymesh-api/crates/polymesh-api-codegen-macro/" }

# DART
# Curve tree dependencies
#curve_tree_bulletproofs = { package = "bulletproofs", path = "../../curve-trees/bulletproofs" }
#curve_tree_relations = { package = "relations", path = "../../curve-trees/relations" }
#ark-ec-divisors = { package = "ark-ec-divisors", path = "../../curve-trees/ark-ec-divisors"}
#ark-dlog-gadget = { package = "ark-dlog-gadget", path = "../../curve-trees/ark-dlog-gadget"}
# If want to pull code for curve-trees from git, comment above 2 relations and uncomment below 2
curve_tree_bulletproofs = { package = "bulletproofs", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }
curve_tree_relations = { package = "relations", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }
ark-ec-divisors = { package = "ark-ec-divisors", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }
ark-dlog-gadget = { package = "ark-dlog-gadget", git = "https://github.com/PolymeshAssociation/curve-trees", branch = "polymesh" }

#dock_crypto_utils = { path = "../../crypto/utils" }
#schnorr_pok = { path = "../../crypto/schnorr_pok" }
dock_crypto_utils = { git = "https://github.com/PolymeshAssociation/crypto", branch = "main" }
schnorr_pok = { git = "https://github.com/PolymeshAssociation/crypto", branch = "main" }

#polymesh-dart = { path = "../../polymesh-dart" }
#polymesh-dart-bp = { path = "../../polymesh-dart/dart-bp" }
#polymesh-dart-common = { path = "../../polymesh-dart/dart-common" }
polymesh-dart = { git = "https://github.com/PolymeshAssociation/polymesh-dart", branch = "main" }
polymesh-dart-bp = { git = "https://github.com/PolymeshAssociation/polymesh-dart", branch = "main" }
polymesh-dart-common = { git = "https://github.com/PolymeshAssociation/polymesh-dart", branch = "main" }

# Polymesh changes to Arkworks.
#ark-serialize = { path = "../../arkworks-algebra/serialize" }
#ark-ec = { path = "../../arkworks-algebra/ec" }
#ark-ff = { path = "../../arkworks-algebra/ff" }
#ark-pallas = { path = "../../arkworks-algebra/curves/pallas" }
#ark-vesta = { path = "../../arkworks-algebra/curves/vesta" }
#ark-helios = { path = "../../arkworks-algebra/curves/helios" }
#ark-selene = { path = "../../arkworks-algebra/curves/selene" }
#ark-wei25519 = { path = "../../arkworks-algebra/curves/wei25519" }
#ark-curve25519 = { path = "../../arkworks-algebra/curves/curve25519" }
#ark-ed25519 = { path = "../../arkworks-algebra/curves/ed25519" }

ark-serialize = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ec = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ff = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-pallas = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-vesta = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-helios = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-selene = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-wei25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-curve25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }
ark-ed25519 = { git = "https://github.com/PolymeshAssociation/arkworks-algebra.git", branch = "polymesh-master" }

[features]
default = ["current_release"]

debug = []

previous_release = [
    "polymesh-api/polymesh_v7",
    "polymesh-api-tester/polymesh_v7",
]
current_release = [
    "polymesh-api/polymesh_v8",
    "polymesh-api-tester/polymesh_v8",
]

[dependencies]
anyhow = "1"
log = "0.4"
test-log = { version = "0.2.17" }

async-trait = { version = "0.1" }
tokio = { version = "1.44.2", features = ["full"] }
serde_json = "1.0.140"
rand = { version = "0.8" }

sp-core = "36.1"
sp-runtime = "41.1"
sp-keyring = "41.0"
sp-weights = "31.1"
codec = { package = "parity-scale-codec", version = "3.0.0", features = [
    "derive",
    "max-encoded-len",
] }

polymesh-api = { version = "3.13.1", default-features = false, features = [
    "download_metadata",
] }
polymesh-api-client-extras = { version = "3.6.3", default-features = false, features = [
    "std",
    "serde",
] }
polymesh-api-tester = { version = "0.10.1", default-features = false, features = [
    "download_metadata",
] }

# DART Assets
polymesh-dart = { version = "0.1.0", default-features = false, features = [
    "std",
    "asm",
    "parallel",
    "backend_bp",
    "async_tree",
] }
ark-ec = { version = "0.5", default-features = false }

[profile.release]
debug = true

# Enable max optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3

[profile.dev]
opt-level = 1

# build scripts, proc macros.
[profile.dev.build-override]
opt-level = 3
