[package]
name = "integration"
version = "0.1.0"
edition = "2021"

# Use these for testing new versions of `polymesh-api`.
#[patch.crates-io]
#polymesh-api = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-client = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-client-extras = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-tester = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-codegen = { git = "https://github.com/PolymeshAssociation/polymesh-api" }
#polymesh-api-codegen-macro = { git = "https://github.com/PolymeshAssociation/polymesh-api" }

[features]
default = []

previous_release = []
current_release = []

[dependencies]
anyhow = "1"
log = "0.4"

async-trait = { version = "0.1" }
tokio = { version = "1.44.2", features = ["full"] }
serde_json = "1.0.140"

sp-core = "36.1"
sp-runtime = "41.1"
sp-keyring = "41.0"
sp-weights = "31.1"
codec = { package = "parity-scale-codec", version = "3.0.0", features = ["derive", "max-encoded-len"] }

polymesh-api = { git = "https://github.com/PolymeshAssociation/polymesh-api", branch = "update-new-type", features = ["download_metadata"] }
polymesh-api-client-extras = { git = "https://github.com/PolymeshAssociation/polymesh-api", branch = "update-new-type", features = ["polymesh_v8"]}
polymesh-api-tester = { git = "https://github.com/PolymeshAssociation/polymesh-api", branch = "update-new-type", features = ["download_metadata"] }
