[package]
name = "pallet-bridge"
version = "1.0.0"
authors = ["PolymeshAssociation"]
edition = "2021"

[dependencies]
polymesh-primitives = { workspace = true, default-features = false }

pallet-balances = { workspace = true, default-features = false }
pallet-base = { workspace = true, default-features = false }
pallet-identity = { workspace = true, default-features = false }
pallet-multisig = { workspace = true, default-features = false }

# Substrate
codec = { workspace = true, default-features = false, features = ["derive"] }
scale-info = { workspace = true, default-features = false, features = ["derive"] }
sp-core = { workspace = true, default-features = false }
sp-std = { workspace = true, default-features = false }
sp-runtime = { workspace = true, default-features = false }
frame-support = { workspace = true, default-features = false }
frame-system = { workspace = true, default-features = false }
pallet-scheduler = { workspace = true, default-features = false }

frame-benchmarking = { workspace = true, default-features = false, optional = true }

# Other
serde = { version = "1.0.104", default-features = false }
log = "0.4.8"

[features]
default = ["std", "equalize"]

equalize = []
only-staking = []
no_std = []
std = [
    "frame-benchmarking?/std",
    "frame-support/std",
    "frame-system/std",
    "pallet-base/std",
    "pallet-balances/std",
    "pallet-identity/std",
    "pallet-multisig/std",
    "pallet-scheduler/std",
    "polymesh-primitives/std",
    "serde/std",
    "sp-core/std",
    "sp-runtime/std",
    "sp-std/std",
]

runtime-benchmarks = [
    "frame-benchmarking"
]
try-runtime = ["frame-support/try-runtime"]
