// This file is part of the Polymesh distribution (https://github.com/PolymeshAssociation/Polymesh).
// Copyright (c) 2026 Polymesh

//! # Worker Modules Pallet
//!
//! This pallet manages updating worker modules for different protocols supported by the Polymesh Worker extension.
//!
//!
//!

#![cfg_attr(not(feature = "std"), no_std)]

use codec::{Decode, DecodeWithMemTracking, Encode, MaxEncodedLen};
use frame_support::traits::ConstU32;
use frame_support::{dispatch::DispatchResult, ensure, traits::Get, weights::Weight, BoundedVec};
use frame_system::pallet_prelude::*;
use scale_info::TypeInfo;
use sp_io::hashing::blake2_256;
use sp_runtime::{Deserialize, Serialize};
use sp_std::vec::Vec;

use polymesh_primitives::GetExtra;
use polymesh_worker_common::{
    BackendCodeHash, BackendContextHash, BackendModuleDefinition, Protocol, ProtocolId,
    ProtocolModuleConfigHash, ProtocolVersion,
};

#[cfg(feature = "runtime-benchmarks")]
pub mod benchmarking;

pub mod weights;

pub trait WeightInfo {
    fn register_protocol() -> Weight;
    fn upload_protocol_module_code() -> Weight;
    fn upload_protocol_module_context() -> Weight;
    fn upload_protocol_module_config(m: u32) -> Weight;
}

/// Protocol metadata for a protocol supported by the Polymesh Worker extension.
#[derive(
    Clone,
    Encode,
    Decode,
    Serialize,
    Deserialize,
    PartialEq,
    Eq,
    Default,
    Debug,
    MaxEncodedLen,
    TypeInfo,
    DecodeWithMemTracking
)]
pub struct ProtocolMetadata {
    /// The protocol name.
    pub protocol_name: BoundedVec<u8, ConstU32<64>>,
    /// The protocol description.
    pub protocol_description: BoundedVec<u8, ConstU32<256>>,
    /// The protocol version.
    pub protocol_version: ProtocolVersion,
}

/// Protocol initialization method.
#[derive(
    Clone,
    Debug,
    Encode,
    Decode,
    PartialEq,
    Eq,
    MaxEncodedLen,
    TypeInfo,
    DecodeWithMemTracking
)]
#[scale_info(skip_type_params(MaxModuleContextSize))]
pub enum ProtocolInitializationMethod<MaxModuleContextSize: Get<u32>> {
    /// No initialization is needed, the module can be used directly after loading.
    NoInitializationNeeded,
    /// Initialize with no context.
    InitializeNoContext,
    /// Initialize the first module instance without context and save the context for faster initialization of subsequent instances.
    SaveContextFromFirstInstance,
    /// The module needs to be initialized with the given context data, which is generated by the runtime and passed to the host for module initialization.
    ContextData(BoundedVec<u8, MaxModuleContextSize>),
    /// The module needs to be initialized with the given context hash, which is used to load the initialization context data from the cache or from Substrate on-chain storage.
    ContextHash(BackendContextHash),
}

/// A protocol's module configuration, which contains the list of backends and their corresponding module definitions (code hash, context hash, etc).
#[derive(
    Clone,
    Debug,
    Encode,
    Decode,
    PartialEq,
    Eq,
    MaxEncodedLen,
    TypeInfo,
    DecodeWithMemTracking
)]
#[scale_info(skip_type_params(MaxModuleContextSize, MaxModulesPerConfig))]
pub struct ProtocolModuleConfig<MaxModuleContextSize: Get<u32>, MaxModulesPerConfig: Get<u32>> {
    /// The protocol id and version are included here to make sure the config hash includes the protocol information, which is used for caching the loaded module.
    pub protocol: Protocol,
    /// The initialization method for the protocol module, which is used to determine how to initialize the module after loading.
    pub initialization_method: ProtocolInitializationMethod<MaxModuleContextSize>,
    /// The list of backend module definitions for the protocol, which contains the module code hash and context hash for each backend.
    pub modules: BoundedVec<BackendModuleDefinition, MaxModulesPerConfig>,
}

pub use pallet::*;

#[frame_support::pallet]
pub mod pallet {
    use super::*;
    use frame_support::pallet_prelude::*;

    #[pallet::pallet]
    #[pallet::without_storage_info]
    pub struct Pallet<T>(_);

    /// Configuration trait.
    #[pallet::config]
    pub trait Config: frame_system::Config {
        /// Confidential asset pallet weights.
        type WeightInfo: WeightInfo;

        /// Maximum module code size in bytes.
        type MaxModuleCodeSize: GetExtra<u32>;

        /// Maximum module context size in bytes.
        type MaxModuleContextSize: GetExtra<u32>;

        /// Maximum number of modules per protocol config.
        type MaxModulesPerConfig: GetExtra<u32>;
    }

    #[pallet::event]
    #[pallet::generate_deposit(pub(super) fn deposit_event)]
    pub enum Event<T: Config> {
        /// A new protocol has been registered.
        ProtocolRegistered {
            /// The ID of the registered protocol.
            protocol_id: ProtocolId,
            /// The metadata of the registered protocol.
            metadata: ProtocolMetadata,
        },
        /// Protocol module code has been uploaded.
        ProtocolModuleCodeUploaded {
            /// The protocol the module code belongs to.
            protocol: Protocol,
            /// The uploaded module code.
            code: BoundedVec<u8, T::MaxModuleCodeSize>,
            /// The hash of the uploaded module code.
            code_hash: BackendCodeHash,
        },
        /// Protocol module context has been uploaded.
        ProtocolModuleContextUploaded {
            /// The protocol the module context belongs to.
            protocol: Protocol,
            /// The uploaded module context.
            context: BoundedVec<u8, T::MaxModuleContextSize>,
            /// The hash of the uploaded module context.
            context_hash: BackendContextHash,
        },
        /// Protocol module config has been uploaded.
        ProtocolModuleConfigUploaded {
            /// The protocol the module config belongs to.
            protocol: Protocol,
            /// The uploaded module config.
            config: ProtocolModuleConfig<T::MaxModuleContextSize, T::MaxModulesPerConfig>,
            /// The hash of the uploaded module config.
            config_hash: ProtocolModuleConfigHash,
        },
    }

    #[pallet::error]
    pub enum Error<T> {
        /// The protocol is already registered.
        ProtocolAlreadyRegistered,
        /// The protocol is not registered.
        ProtocolNotRegistered,
        /// The protocol metadata is invalid.
        InvalidProtocolMetadata,
        /// The protocol module code already exists.
        ProtocolModuleCodeAlreadyExists,
        /// The protocol module context already exists.
        ProtocolModuleContextAlreadyExists,
        /// The protocol module config already exists.
        ProtocolModuleConfigAlreadyExists,
        /// Module code missing for the given code hash.
        ModuleCodeMissing,
        /// Module context missing for the given context hash.
        ModuleContextMissing,
    }

    /// Protocol metadata storage item, which maps ProtocolId => ProtocolMetadata.
    #[pallet::storage]
    pub type Metadata<T: Config> =
        StorageMap<_, Blake2_128Concat, ProtocolId, ProtocolMetadata, OptionQuery>;

    /// Protocol config hash storage item, which maps Protocol => ProtocolModuleConfigHash.
    #[pallet::storage]
    pub type ProtocolConfigHash<T: Config> =
        StorageMap<_, Identity, Protocol, ProtocolModuleConfigHash, OptionQuery>;

    /// Protocol config storage item, which double maps (Protocol, ProtocolModuleConfigHash) => ProtocolModuleConfig.
    #[pallet::storage]
    pub type ProtocolConfig<T: Config> = StorageDoubleMap<
        _,
        Identity,
        Protocol,
        Identity,
        ProtocolModuleConfigHash,
        ProtocolModuleConfig<T::MaxModuleContextSize, T::MaxModulesPerConfig>,
        OptionQuery,
    >;

    /// Protocol module code storage item, which double maps (Protocol, BackendCodeHash) => Vec<u8>.
    #[pallet::storage]
    pub type ProtocolModuleCode<T: Config> = StorageDoubleMap<
        _,
        Identity,
        Protocol,
        Identity,
        BackendCodeHash,
        BoundedVec<u8, T::MaxModuleCodeSize>,
        OptionQuery,
    >;

    /// Protocol context storage item, which double maps (Protocol, BackendContextHash) => Vec<u8>.
    #[pallet::storage]
    pub type ProtocolContext<T: Config> = StorageDoubleMap<
        _,
        Identity,
        Protocol,
        Identity,
        BackendContextHash,
        BoundedVec<u8, T::MaxModuleContextSize>,
        OptionQuery,
    >;

    #[pallet::genesis_config]
    #[derive(frame_support::DefaultNoBound)]
    pub struct GenesisConfig<T> {
        pub protocols: Vec<(ProtocolId, ProtocolMetadata)>,
        pub _config: sp_std::marker::PhantomData<T>,
    }

    #[pallet::genesis_build]
    impl<T: Config> BuildGenesisConfig for GenesisConfig<T> {
        fn build(&self) {
            for (protocol_id, metadata) in &self.protocols {
                Metadata::<T>::insert(protocol_id, metadata.clone());
            }
        }
    }

    #[pallet::call]
    impl<T: Config> Pallet<T> {
        /// Register a new protocol.
        ///
        /// # Arguments
        /// * `origin` - The origin of the call, must be root.
        /// * `protocol_id` - The ID of the protocol to register.
        /// * `metadata` - The metadata of the protocol to register.
        ///
        /// # Errors
        /// * `DispatchError::BadOrigin` - If the origin is not root.
        /// * `Error::<T>::ProtocolAlreadyRegistered` - If the protocol is already registered.
        /// * `Error::<T>::InvalidProtocolMetadata` - If the protocol metadata is invalid.
        #[pallet::call_index(0)]
        #[pallet::weight(<T as Config>::WeightInfo::register_protocol())]
        pub fn register_protocol(
            origin: OriginFor<T>,
            protocol_id: ProtocolId,
            metadata: ProtocolMetadata,
        ) -> DispatchResult {
            ensure_root(origin)?;

            // Ensure the protocol is not already registered.
            ensure!(
                !Metadata::<T>::contains_key(&protocol_id),
                Error::<T>::ProtocolAlreadyRegistered
            );

            // Ensure the protocol metadata is valid.
            ensure!(
                !metadata.protocol_name.is_empty(),
                Error::<T>::InvalidProtocolMetadata
            );

            // Store the protocol metadata.
            Metadata::<T>::insert(&protocol_id, &metadata);

            // Emit an event.
            Self::deposit_event(Event::ProtocolRegistered {
                protocol_id,
                metadata,
            });

            Ok(())
        }

        /// Upload protocol module code.
        ///
        /// # Arguments
        /// * `origin` - The origin of the call, must be root.
        /// * `protocol` - The protocol to upload the module code for.
        /// * `code` - The module code to upload.
        ///
        /// # Errors
        /// * `DispatchError::BadOrigin` - If the origin is not root.
        /// * `Error::<T>::ProtocolNotRegistered` - If the protocol is not registered.
        /// * `Error::<T>::ProtocolModuleCodeAlreadyExists` - If the protocol module code already exists.
        #[pallet::call_index(1)]
        #[pallet::weight(<T as Config>::WeightInfo::upload_protocol_module_code())]
        pub fn upload_protocol_module_code(
            origin: OriginFor<T>,
            protocol: Protocol,
            code: BoundedVec<u8, T::MaxModuleCodeSize>,
        ) -> DispatchResult {
            ensure_root(origin)?;

            // Ensure the protocol is registered.
            ensure!(
                Metadata::<T>::contains_key(&protocol.id),
                Error::<T>::ProtocolNotRegistered
            );

            let code_hash = code.using_encoded(blake2_256);
            // Ensure the code hash is not already stored for the protocol.
            ensure!(
                !ProtocolModuleCode::<T>::contains_key(&protocol, &code_hash),
                Error::<T>::ProtocolModuleCodeAlreadyExists
            );

            // Store the protocol module code.
            ProtocolModuleCode::<T>::insert(&protocol, &code_hash, &code);

            // Emit an event.
            Self::deposit_event(Event::ProtocolModuleCodeUploaded {
                protocol,
                code,
                code_hash,
            });

            Ok(())
        }

        /// Upload protocol module context.
        ///
        /// # Arguments
        /// * `origin` - The origin of the call, must be root.
        /// * `protocol` - The protocol to upload the module context for.
        /// * `context` - The module context to upload.
        ///
        /// # Errors
        /// * `DispatchError::BadOrigin` - If the origin is not root.
        /// * `Error::<T>::ProtocolNotRegistered` - If the protocol is not registered.
        /// * `Error::<T>::ProtocolModuleContextAlreadyExists` - If the protocol module context already exists.
        #[pallet::call_index(2)]
        #[pallet::weight(<T as Config>::WeightInfo::upload_protocol_module_context())]
        pub fn upload_protocol_module_context(
            origin: OriginFor<T>,
            protocol: Protocol,
            context: BoundedVec<u8, T::MaxModuleContextSize>,
        ) -> DispatchResult {
            ensure_root(origin)?;

            // Ensure the protocol is registered.
            ensure!(
                Metadata::<T>::contains_key(&protocol.id),
                Error::<T>::ProtocolNotRegistered
            );

            let context_hash = context.using_encoded(blake2_256);
            // Ensure the context hash is not already stored for the protocol.
            ensure!(
                !ProtocolContext::<T>::contains_key(&protocol, &context_hash),
                Error::<T>::ProtocolModuleContextAlreadyExists
            );

            // Store the protocol module context.
            ProtocolContext::<T>::insert(&protocol, &context_hash, &context);

            // Emit an event.
            Self::deposit_event(Event::ProtocolModuleContextUploaded {
                protocol,
                context,
                context_hash,
            });
            Ok(())
        }

        /// Upload protocol module config.
        ///
        /// # Arguments
        /// * `origin` - The origin of the call, must be root.
        /// * `protocol` - The protocol to upload the module config for.
        /// * `config` - The module config to upload.
        ///
        /// # Errors
        /// * `DispatchError::BadOrigin` - If the origin is not root.
        /// * `Error::<T>::ProtocolNotRegistered` - If the protocol is not registered.
        /// * `Error::<T>::ProtocolModuleConfigAlreadyExists` - If the protocol module config already exists.
        #[pallet::call_index(3)]
        #[pallet::weight(<T as Config>::WeightInfo::upload_protocol_module_config(config.modules.len() as u32))]
        pub fn upload_protocol_module_config(
            origin: OriginFor<T>,
            protocol: Protocol,
            config: ProtocolModuleConfig<T::MaxModuleContextSize, T::MaxModulesPerConfig>,
        ) -> DispatchResult {
            ensure_root(origin)?;

            // Ensure the protocol is registered.
            ensure!(
                Metadata::<T>::contains_key(&protocol.id),
                Error::<T>::ProtocolNotRegistered
            );

            let config_hash = config.using_encoded(blake2_256);
            // Ensure the config hash is not already stored for the protocol.
            ensure!(
                !ProtocolConfig::<T>::contains_key(&protocol, &config_hash),
                Error::<T>::ProtocolModuleConfigAlreadyExists
            );

            // Ensure the context hashes exist for the protocol.
            match &config.initialization_method {
                ProtocolInitializationMethod::ContextHash(context_hash) => {
                    ensure!(
                        ProtocolContext::<T>::contains_key(&protocol, &context_hash),
                        Error::<T>::ModuleContextMissing
                    );
                }
                _ => {}
            }

            // Ensure all module code hashes exist for the protocol.
            for module in &config.modules {
                ensure!(
                    ProtocolModuleCode::<T>::contains_key(&protocol, &module.code_hash),
                    Error::<T>::ModuleCodeMissing
                );
            }

            // Store the protocol module config.
            ProtocolConfig::<T>::insert(&protocol, &config_hash, &config);

            // Point the protocol to the latest config hash for the protocol.
            // This allows updating the protocol config.
            ProtocolConfigHash::<T>::insert(&protocol, &config_hash);

            // Emit an event.
            Self::deposit_event(Event::ProtocolModuleConfigUploaded {
                protocol,
                config,
                config_hash,
            });
            Ok(())
        }
    }
}
