// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_staking
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-12-02, STEPS: `100`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `ubuntu-8gb-nbg1-1-bench2`, CPU: `AMD EPYC-Milan Processor`
//! HOSTNAME: `ubuntu-8gb-nbg1-1-bench2`, CPU: `AMD EPYC-Milan Processor`

// Executed Command:
// ./polymesh
// benchmark
// pallet
// -s
// 100
// -r
// 5
// -p=pallet_staking
// -e=*
// --heap-pages
// 4096
// --db-cache
// 512
// --execution
// wasm
// --wasm-execution
// compiled
// --output
// ./Polymesh/pallets/weights/src/
// --template
// ./Polymesh/.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_primitives::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_staking using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl pallet_staking::WeightInfo for SubstrateWeight {
    // Storage: Staking Bonded (r:1 w:1)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:2 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking CurrentEra (r:1 w:0)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Payee (r:0 w:1)
    // Proof: Staking Payee (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    fn bond() -> Weight {
        // Minimum execution time: 60_331 nanoseconds.
        Weight::from_parts(70_966_000, 0)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: Staking Bonded (r:1 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:1 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:1 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    fn bond_extra() -> Weight {
        // Minimum execution time: 57_987 nanoseconds.
        Weight::from_parts(62_364_000, 0)
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Staking Ledger (r:1 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:1 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking CurrentEra (r:1 w:0)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: System Account (r:1 w:1)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity IsDidFrozen (r:1 w:0)
    // Proof Skipped: Identity IsDidFrozen (max_values: None, max_size: None, mode: Measured)
    fn unbond() -> Weight {
        // Minimum execution time: 61_993 nanoseconds.
        Weight::from_parts(65_178_000, 0)
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(3))
    }
    // Storage: Staking Ledger (r:1 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking CurrentEra (r:1 w:0)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: System Account (r:1 w:1)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// The range of component `s` is `[0, 100]`.
    fn withdraw_unbonded_update(s: u32) -> Weight {
        // Minimum execution time: 39_089 nanoseconds.
        Weight::from_parts(43_312_712, 0)
            // Standard Error: 9_035
            .saturating_add(Weight::from_parts(23_827, 0).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes(3))
    }
    // Storage: Staking Ledger (r:1 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking CurrentEra (r:1 w:0)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Bonded (r:1 w:1)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking SlashingSpans (r:1 w:1)
    // Proof Skipped: Staking SlashingSpans (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Validators (r:1 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: System Account (r:1 w:1)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Payee (r:0 w:1)
    // Proof: Staking Payee (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Staking SpanSlash (r:0 w:99)
    // Proof: Staking SpanSlash (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
    /// The range of component `s` is `[0, 100]`.
    fn withdraw_unbonded_kill(s: u32) -> Weight {
        // Minimum execution time: 65_528 nanoseconds.
        Weight::from_parts(70_402_882, 0)
            // Standard Error: 20_479
            .saturating_add(Weight::from_parts(1_555_243, 0).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(6))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(s.into())))
    }
    // Storage: Staking Ledger (r:1 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:1 w:0)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: Staking MinCommission (r:1 w:0)
    // Proof: Staking MinCommission (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking ValidatorCommissionCap (r:1 w:0)
    // Proof: Staking ValidatorCommissionCap (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking PermissionedIdentity (r:1 w:1)
    // Proof Skipped: Staking PermissionedIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Validators (r:1 w:1)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking MaxValidatorsCount (r:1 w:0)
    // Proof: Staking MaxValidatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Identity AccountKeyRefCount (r:1 w:1)
    // Proof Skipped: Identity AccountKeyRefCount (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Staking Bonded (r:1 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking CounterForValidators (r:1 w:1)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    fn validate() -> Weight {
        // Minimum execution time: 67_872 nanoseconds.
        Weight::from_parts(71_938_000, 0)
            .saturating_add(DbWeight::get().reads(12))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: Staking Ledger (r:1 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:128 w:128)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    /// The range of component `k` is `[1, 128]`.
    fn kick(k: u32) -> Weight {
        // Minimum execution time: 34_292 nanoseconds.
        Weight::from_parts(33_550_562, 0)
            // Standard Error: 22_924
            .saturating_add(Weight::from_parts(8_737_552, 0).saturating_mul(k.into()))
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(k.into())))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(k.into())))
    }
    // Storage: Staking Ledger (r:1 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking MinNominatorBond (r:1 w:0)
    // Proof: Staking MinNominatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:1)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Staking MaxNominatorsCount (r:1 w:0)
    // Proof: Staking MaxNominatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:17 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:2 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking CurrentEra (r:1 w:0)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Bonded (r:1 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking CounterForNominators (r:1 w:1)
    // Proof: Staking CounterForNominators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    /// The range of component `n` is `[1, 16]`.
    fn nominate(n: u32) -> Weight {
        // Minimum execution time: 83_956 nanoseconds.
        Weight::from_parts(86_634_894, 0)
            // Standard Error: 69_456
            .saturating_add(Weight::from_parts(4_443_175, 0).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(13))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Staking Ledger (r:1 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:1 w:1)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking PermissionedIdentity (r:1 w:1)
    // Proof Skipped: Staking PermissionedIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity AccountKeyRefCount (r:1 w:1)
    // Proof Skipped: Identity AccountKeyRefCount (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking CounterForValidators (r:1 w:1)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    fn chill() -> Weight {
        // Minimum execution time: 56_475 nanoseconds.
        Weight::from_parts(57_165_000, 0)
            .saturating_add(DbWeight::get().reads(7))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: Staking Ledger (r:1 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Payee (r:0 w:1)
    // Proof: Staking Payee (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    fn set_payee() -> Weight {
        // Minimum execution time: 17_556 nanoseconds.
        Weight::from_parts(17_957_000, 0)
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking Bonded (r:1 w:1)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:3 w:2)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    fn set_controller() -> Weight {
        // Minimum execution time: 29_294 nanoseconds.
        Weight::from_parts(31_197_000, 0)
            .saturating_add(DbWeight::get().reads(4))
            .saturating_add(DbWeight::get().writes(3))
    }
    // Storage: Staking ValidatorCount (r:0 w:1)
    // Proof: Staking ValidatorCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    fn set_validator_count() -> Weight {
        // Minimum execution time: 3_065 nanoseconds.
        Weight::from_parts(3_475_000, 0).saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking ForceEra (r:0 w:1)
    // Proof: Staking ForceEra (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
    fn force_no_eras() -> Weight {
        // Minimum execution time: 12_188 nanoseconds.
        Weight::from_parts(18_618_000, 0).saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking ForceEra (r:0 w:1)
    // Proof: Staking ForceEra (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
    fn force_new_era() -> Weight {
        // Minimum execution time: 10_927 nanoseconds.
        Weight::from_parts(11_928_000, 0).saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking ForceEra (r:0 w:1)
    // Proof: Staking ForceEra (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
    fn force_new_era_always() -> Weight {
        // Minimum execution time: 10_716 nanoseconds.
        Weight::from_parts(11_498_000, 0).saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking Invulnerables (r:0 w:1)
    // Proof Skipped: Staking Invulnerables (max_values: Some(1), max_size: None, mode: Measured)
    /// The range of component `v` is `[0, 100]`.
    fn set_invulnerables(v: u32) -> Weight {
        // Minimum execution time: 3_135 nanoseconds.
        Weight::from_parts(5_195_193, 0)
            // Standard Error: 4_599
            .saturating_add(Weight::from_parts(4_304, 0).saturating_mul(v.into()))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking Bonded (r:1 w:1)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking SlashingSpans (r:1 w:1)
    // Proof Skipped: Staking SlashingSpans (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Validators (r:1 w:1)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking CounterForValidators (r:1 w:1)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: System Account (r:1 w:1)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Ledger (r:0 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Payee (r:0 w:1)
    // Proof: Staking Payee (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Staking SpanSlash (r:0 w:99)
    // Proof: Staking SpanSlash (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
    /// The range of component `s` is `[0, 100]`.
    fn force_unstake(s: u32) -> Weight {
        // Minimum execution time: 53_891 nanoseconds.
        Weight::from_parts(61_359_846, 0)
            // Standard Error: 14_648
            .saturating_add(Weight::from_parts(1_530_947, 0).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(7))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(s.into())))
    }
    // Storage: Staking UnappliedSlashes (r:1 w:1)
    // Proof Skipped: Staking UnappliedSlashes (max_values: None, max_size: None, mode: Measured)
    /// The range of component `s` is `[1, 1000]`.
    fn cancel_deferred_slash(s: u32) -> Weight {
        // Minimum execution time: 113_771 nanoseconds.
        Weight::from_parts(1_128_694_838, 0)
            // Standard Error: 90_787
            .saturating_add(Weight::from_parts(5_999_718, 0).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking CurrentEra (r:1 w:0)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking ErasValidatorReward (r:1 w:0)
    // Proof: Staking ErasValidatorReward (max_values: None, max_size: Some(28), added: 2503, mode: MaxEncodedLen)
    // Storage: Staking Bonded (r:1025 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:1025 w:1025)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking ErasStakersClipped (r:1 w:0)
    // Proof Skipped: Staking ErasStakersClipped (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking ErasRewardPoints (r:1 w:0)
    // Proof Skipped: Staking ErasRewardPoints (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking ErasValidatorPrefs (r:1 w:0)
    // Proof: Staking ErasValidatorPrefs (max_values: None, max_size: Some(57), added: 2532, mode: MaxEncodedLen)
    // Storage: Staking Payee (r:1025 w:0)
    // Proof: Staking Payee (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: System Account (r:1026 w:1026)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1025 w:1025)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1026 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    /// The range of component `n` is `[0, 1024]`.
    fn payout_stakers_alive_staked(n: u32) -> Weight {
        // Minimum execution time: 220_430 nanoseconds.
        Weight::from_parts(367_311_716, 0)
            // Standard Error: 54_323
            .saturating_add(Weight::from_parts(48_316_458, 0).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(13))
            .saturating_add(DbWeight::get().reads((6_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(4))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(n.into())))
    }
    // Storage: Staking Ledger (r:1 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: System Account (r:1 w:1)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:1 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    /// The range of component `l` is `[1, 32]`.
    fn rebond(l: u32) -> Weight {
        // Minimum execution time: 43_566 nanoseconds.
        Weight::from_parts(47_774_541, 0)
            // Standard Error: 22_727
            .saturating_add(Weight::from_parts(83_350, 0).saturating_mul(l.into()))
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().writes(3))
    }
    // Storage: System Account (r:1 w:1)
    // Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    // Storage: Staking Bonded (r:1 w:1)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking SlashingSpans (r:1 w:1)
    // Proof Skipped: Staking SlashingSpans (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Validators (r:1 w:1)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking CounterForValidators (r:1 w:1)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Balances Locks (r:1 w:1)
    // Proof Skipped: Balances Locks (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Ledger (r:0 w:1)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Payee (r:0 w:1)
    // Proof: Staking Payee (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Staking SpanSlash (r:0 w:100)
    // Proof: Staking SpanSlash (max_values: None, max_size: Some(76), added: 2551, mode: MaxEncodedLen)
    /// The range of component `s` is `[1, 100]`.
    fn reap_stash(s: u32) -> Weight {
        // Minimum execution time: 75_182 nanoseconds.
        Weight::from_parts(78_034_699, 0)
            // Standard Error: 13_681
            .saturating_add(Weight::from_parts(1_564_606, 0).saturating_mul(s.into()))
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().writes(8))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(s.into())))
    }
    // Storage: ElectionProviderMultiPhase SignedSubmissionIndices (r:1 w:1)
    // Proof Skipped: ElectionProviderMultiPhase SignedSubmissionIndices (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: ElectionProviderMultiPhase SignedSubmissionNextIndex (r:1 w:1)
    // Proof Skipped: ElectionProviderMultiPhase SignedSubmissionNextIndex (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: ElectionProviderMultiPhase SnapshotMetadata (r:1 w:1)
    // Proof Skipped: ElectionProviderMultiPhase SnapshotMetadata (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: ElectionProviderMultiPhase SignedSubmissionsMap (r:1 w:0)
    // Proof Skipped: ElectionProviderMultiPhase SignedSubmissionsMap (max_values: None, max_size: None, mode: Measured)
    // Storage: System BlockWeight (r:1 w:1)
    // Proof: System BlockWeight (max_values: Some(1), max_size: Some(48), added: 543, mode: MaxEncodedLen)
    // Storage: ElectionProviderMultiPhase QueuedSolution (r:1 w:0)
    // Proof Skipped: ElectionProviderMultiPhase QueuedSolution (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Staking CounterForNominators (r:1 w:0)
    // Proof: Staking CounterForNominators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking CounterForValidators (r:1 w:0)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:11 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:110 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:109 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:218 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking PermissionedIdentity (r:10 w:0)
    // Proof Skipped: Staking PermissionedIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Bonded (r:109 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:109 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:1 w:0)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: Staking ValidatorCount (r:1 w:0)
    // Proof: Staking ValidatorCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: ElectionProviderMultiPhase Round (r:1 w:1)
    // Proof Skipped: ElectionProviderMultiPhase Round (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: ElectionProviderMultiPhase CurrentPhase (r:1 w:1)
    // Proof Skipped: ElectionProviderMultiPhase CurrentPhase (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Staking MinimumValidatorCount (r:1 w:0)
    // Proof: Staking MinimumValidatorCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking CurrentEra (r:1 w:1)
    // Proof: Staking CurrentEra (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking ErasStakersClipped (r:0 w:10)
    // Proof Skipped: Staking ErasStakersClipped (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking ErasValidatorPrefs (r:0 w:10)
    // Proof: Staking ErasValidatorPrefs (max_values: None, max_size: Some(57), added: 2532, mode: MaxEncodedLen)
    // Storage: Staking ErasStakers (r:0 w:10)
    // Proof Skipped: Staking ErasStakers (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking ErasTotalStake (r:0 w:1)
    // Proof: Staking ErasTotalStake (max_values: None, max_size: Some(28), added: 2503, mode: MaxEncodedLen)
    // Storage: Staking ErasStartSessionIndex (r:0 w:1)
    // Proof: Staking ErasStartSessionIndex (max_values: None, max_size: Some(16), added: 2491, mode: MaxEncodedLen)
    // Storage: Staking MinimumActiveStake (r:0 w:1)
    // Proof: Staking MinimumActiveStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: ElectionProviderMultiPhase DesiredTargets (r:0 w:1)
    // Proof Skipped: ElectionProviderMultiPhase DesiredTargets (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: ElectionProviderMultiPhase Snapshot (r:0 w:1)
    // Proof Skipped: ElectionProviderMultiPhase Snapshot (max_values: Some(1), max_size: None, mode: Measured)
    /// The range of component `v` is `[1, 10]`.
    /// The range of component `n` is `[0, 100]`.
    fn new_era(v: u32, n: u32) -> Weight {
        // Minimum execution time: 837_364 nanoseconds.
        Weight::from_parts(838_106_000, 0)
            // Standard Error: 2_993_345
            .saturating_add(Weight::from_parts(70_132_293, 0).saturating_mul(v.into()))
            // Standard Error: 308_742
            .saturating_add(Weight::from_parts(34_964_910, 0).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(18))
            .saturating_add(DbWeight::get().reads((8_u64).saturating_mul(v.into())))
            .saturating_add(DbWeight::get().reads((6_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(12))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(v.into())))
    }
    // Storage: Staking CounterForNominators (r:1 w:0)
    // Proof: Staking CounterForNominators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking CounterForValidators (r:1 w:0)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:101 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:201 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:200 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:400 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking PermissionedIdentity (r:100 w:0)
    // Proof Skipped: Staking PermissionedIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Bonded (r:200 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:200 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:1 w:0)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: System BlockWeight (r:1 w:1)
    // Proof: System BlockWeight (max_values: Some(1), max_size: Some(48), added: 543, mode: MaxEncodedLen)
    // Storage: Staking MinimumActiveStake (r:0 w:1)
    // Proof: Staking MinimumActiveStake (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    /// The range of component `v` is `[50, 100]`.
    /// The range of component `n` is `[50, 100]`.
    fn get_npos_voters(v: u32, n: u32) -> Weight {
        // Minimum execution time: 5_694_021 nanoseconds.
        Weight::from_parts(5_725_067_000, 0)
            // Standard Error: 703_888
            .saturating_add(Weight::from_parts(12_221_363, 0).saturating_mul(v.into()))
            // Standard Error: 703_888
            .saturating_add(Weight::from_parts(3_495_830, 0).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(8))
            .saturating_add(DbWeight::get().reads((8_u64).saturating_mul(v.into())))
            .saturating_add(DbWeight::get().reads((6_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: Staking CounterForValidators (r:1 w:0)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:101 w:0)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:100 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Instance2Group ActiveMembers (r:1 w:0)
    // Proof Skipped: Instance2Group ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:200 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking PermissionedIdentity (r:100 w:0)
    // Proof Skipped: Staking PermissionedIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking Bonded (r:100 w:0)
    // Proof: Staking Bonded (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Staking Ledger (r:100 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:1 w:0)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: System BlockWeight (r:1 w:1)
    // Proof: System BlockWeight (max_values: Some(1), max_size: Some(48), added: 543, mode: MaxEncodedLen)
    /// The range of component `v` is `[50, 100]`.
    fn get_npos_targets(v: u32) -> Weight {
        // Minimum execution time: 1_999_726 nanoseconds.
        Weight::from_parts(59_228_490, 0)
            // Standard Error: 120_461
            .saturating_add(Weight::from_parts(39_021_437, 0).saturating_mul(v.into()))
            .saturating_add(DbWeight::get().reads(6))
            .saturating_add(DbWeight::get().reads((7_u64).saturating_mul(v.into())))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking MinCommission (r:0 w:1)
    // Proof: Staking MinCommission (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:0 w:1)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: Staking MaxValidatorsCount (r:0 w:1)
    // Proof: Staking MaxValidatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking ChillThreshold (r:0 w:1)
    // Proof: Staking ChillThreshold (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
    // Storage: Staking MaxNominatorsCount (r:0 w:1)
    // Proof: Staking MaxNominatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking MinNominatorBond (r:0 w:1)
    // Proof: Staking MinNominatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn set_staking_configs_all_set() -> Weight {
        // Minimum execution time: 7_441 nanoseconds.
        Weight::from_parts(8_243_000, 0).saturating_add(DbWeight::get().writes(6))
    }
    // Storage: Staking MinCommission (r:0 w:1)
    // Proof: Staking MinCommission (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:0 w:1)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: Staking MaxValidatorsCount (r:0 w:1)
    // Proof: Staking MaxValidatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking ChillThreshold (r:0 w:1)
    // Proof: Staking ChillThreshold (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
    // Storage: Staking MaxNominatorsCount (r:0 w:1)
    // Proof: Staking MaxNominatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking MinNominatorBond (r:0 w:1)
    // Proof: Staking MinNominatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    fn set_staking_configs_all_remove() -> Weight {
        // Minimum execution time: 6_690 nanoseconds.
        Weight::from_parts(15_123_000, 0).saturating_add(DbWeight::get().writes(6))
    }
    // Storage: Staking Ledger (r:1 w:0)
    // Proof: Staking Ledger (max_values: None, max_size: Some(1091), added: 3566, mode: MaxEncodedLen)
    // Storage: Staking Nominators (r:1 w:0)
    // Proof: Staking Nominators (max_values: None, max_size: Some(558), added: 3033, mode: MaxEncodedLen)
    // Storage: Staking ChillThreshold (r:1 w:0)
    // Proof: Staking ChillThreshold (max_values: Some(1), max_size: Some(1), added: 496, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:1 w:1)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    // Storage: Staking MaxValidatorsCount (r:1 w:0)
    // Proof: Staking MaxValidatorsCount (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking CounterForValidators (r:1 w:1)
    // Proof: Staking CounterForValidators (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking MinValidatorBond (r:1 w:0)
    // Proof: Staking MinValidatorBond (max_values: Some(1), max_size: Some(16), added: 511, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof Skipped: Identity KeyRecords (max_values: None, max_size: None, mode: Measured)
    // Storage: Staking PermissionedIdentity (r:1 w:1)
    // Proof Skipped: Staking PermissionedIdentity (max_values: None, max_size: None, mode: Measured)
    // Storage: Identity AccountKeyRefCount (r:1 w:1)
    // Proof Skipped: Identity AccountKeyRefCount (max_values: None, max_size: None, mode: Measured)
    fn chill_other() -> Weight {
        // Minimum execution time: 74_131 nanoseconds.
        Weight::from_parts(75_763_000, 0)
            .saturating_add(DbWeight::get().reads(10))
            .saturating_add(DbWeight::get().writes(4))
    }
    // Storage: Staking MinCommission (r:1 w:0)
    // Proof: Staking MinCommission (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    // Storage: Staking Validators (r:1 w:1)
    // Proof: Staking Validators (max_values: None, max_size: Some(45), added: 2520, mode: MaxEncodedLen)
    fn force_apply_min_commission() -> Weight {
        // Minimum execution time: 16_385 nanoseconds.
        Weight::from_parts(18_157_000, 0)
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: Staking MinCommission (r:0 w:1)
    // Proof: Staking MinCommission (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    fn set_min_commission() -> Weight {
        // Minimum execution time: 3_144 nanoseconds.
        Weight::from_parts(3_806_000, 0).saturating_add(DbWeight::get().writes(1))
    }
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:1 w:1)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    fn update_payee() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `266`
        //  Estimated: `4556`
        // Minimum execution time: 18_991_000 picoseconds.
        Weight::from_parts(19_621_000, 4556)
            .saturating_add(DbWeight::get().reads(3_u64))
            .saturating_add(DbWeight::get().writes(1_u64))
    }
    /// Storage: `Staking::Ledger` (r:11800 w:11800)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:5900 w:5900)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Payee` (r:5900 w:0)
    /// Proof: `Staking::Payee` (`max_values`: None, `max_size`: Some(73), added: 2548, mode: `MaxEncodedLen`)
    /// The range of component `u` is `[0, 5900]`.
    fn deprecate_controller_batch(u: u32) -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1015 + u * (229 ±0)`
        //  Estimated: `990 + u * (7132 ±0)`
        // Minimum execution time: 4_048_000 picoseconds.
        Weight::from_parts(4_168_000, 990)
            // Standard Error: 78_180
            .saturating_add(Weight::from_parts(34_730_792, 0).saturating_mul(u.into()))
            .saturating_add(DbWeight::get().reads((4_u64).saturating_mul(u.into())))
            .saturating_add(DbWeight::get().writes((3_u64).saturating_mul(u.into())))
            .saturating_add(Weight::from_parts(0, 7132).saturating_mul(u.into()))
    }
    /// Storage: `System::Account` (r:1 w:0)
    /// Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:0)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:0)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:1)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:1)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
    fn restore_ledger() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `223`
        //  Estimated: `4764`
        // Minimum execution time: 38_029_000 picoseconds.
        Weight::from_parts(38_545_000, 4764)
            .saturating_add(DbWeight::get().reads(6_u64))
            .saturating_add(DbWeight::get().writes(2_u64))
    }
    /// Storage: `Staking::VirtualStakers` (r:1 w:0)
    /// Proof: `Staking::VirtualStakers` (`max_values`: None, `max_size`: Some(40), added: 2515, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Bonded` (r:1 w:0)
    /// Proof: `Staking::Bonded` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Ledger` (r:1 w:0)
    /// Proof: `Staking::Ledger` (`max_values`: None, `max_size`: Some(1091), added: 3566, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Locks` (r:1 w:1)
    /// Proof: `Balances::Locks` (`max_values`: None, `max_size`: Some(1299), added: 3774, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Freezes` (r:1 w:0)
    /// Proof: `Balances::Freezes` (`max_values`: None, `max_size`: Some(85), added: 2560, mode: `MaxEncodedLen`)
    /// Storage: `Balances::Holds` (r:1 w:1)
    /// Proof: `Balances::Holds` (`max_values`: None, `max_size`: Some(427), added: 2902, mode: `MaxEncodedLen`)
    fn migrate_currency() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `389`
        //  Estimated: `4764`
        // Minimum execution time: 77_496_000 picoseconds.
        Weight::from_parts(78_353_000, 4764)
            .saturating_add(DbWeight::get().reads(6_u64))
            .saturating_add(DbWeight::get().writes(2_u64))
    }
    /// Storage: `Staking::CurrentEra` (r:1 w:0)
    /// Proof: `Staking::CurrentEra` (`max_values`: Some(1), `max_size`: Some(4), added: 499, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStartSessionIndex` (r:1 w:0)
    /// Proof: `Staking::ErasStartSessionIndex` (`max_values`: None, `max_size`: Some(16), added: 2491, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ActiveEra` (r:1 w:0)
    /// Proof: `Staking::ActiveEra` (`max_values`: Some(1), `max_size`: Some(13), added: 508, mode: `MaxEncodedLen`)
    /// Storage: `Staking::Invulnerables` (r:1 w:0)
    /// Proof: `Staking::Invulnerables` (`max_values`: Some(1), `max_size`: Some(641), added: 1136, mode: `MaxEncodedLen`)
    /// Storage: `Staking::ErasStakersOverview` (r:1 w:0)
    /// Proof: `Staking::ErasStakersOverview` (`max_values`: None, `max_size`: Some(92), added: 2567, mode: `MaxEncodedLen`)
    /// Storage: `Session::DisabledValidators` (r:1 w:1)
    /// Proof: `Session::DisabledValidators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Session::Validators` (r:1 w:0)
    /// Proof: `Session::Validators` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    /// Storage: `Staking::ValidatorSlashInEra` (r:1 w:1)
    /// Proof: `Staking::ValidatorSlashInEra` (`max_values`: None, `max_size`: Some(72), added: 2547, mode: `MaxEncodedLen`)
    /// Storage: `Staking::OffenceQueue` (r:1 w:1)
    /// Proof: `Staking::OffenceQueue` (`max_values`: None, `max_size`: Some(101), added: 2576, mode: `MaxEncodedLen`)
    /// Storage: `Staking::OffenceQueueEras` (r:1 w:1)
    /// Proof: `Staking::OffenceQueueEras` (`max_values`: Some(1), `max_size`: Some(2690), added: 3185, mode: `MaxEncodedLen`)
    fn manual_slash() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `514`
        //  Estimated: `4175`
        // Minimum execution time: 30_000_000 picoseconds.
        Weight::from_parts(33_000_000, 4175)
            .saturating_add(DbWeight::get().reads(10_u64))
            .saturating_add(DbWeight::get().writes(4_u64))
    }
}
