// This file is part of the Polymesh distribution (https://github.com/PolymeshAssociation/Polymesh).
// Copyright (c) 2023 Polymesh

//! Autogenerated weights for pallet_timestamp
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-11, STEPS: `100`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `ubuntu-8gb-hel1-bench`, CPU: `AMD EPYC-Milan Processor`

// Executed Command:
// ./target/release/polymesh
// benchmark
// pallet
// -s
// 100
// -r
// 5
// -p=pallet_timestamp
// -e=*
// --heap-pages
// 4096
// --db-cache
// 512
// --output
// ./pallets/weights/src/
// --template
// ./.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_primitives::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_timestamp using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl pallet_timestamp::WeightInfo for SubstrateWeight {
    // Storage: `Timestamp::Now` (r:1 w:1)
    // Proof: `Timestamp::Now` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    // Storage: `Babe::CurrentSlot` (r:1 w:0)
    // Proof: `Babe::CurrentSlot` (`max_values`: Some(1), `max_size`: Some(8), added: 503, mode: `MaxEncodedLen`)
    fn set() -> Weight {
        // Minimum execution time: 10_010 nanoseconds.
        Weight::from_parts(11_230_000, 0)
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(1))
    }
    fn on_finalize() -> Weight {
        // Minimum execution time: 5_300 nanoseconds.
        Weight::from_parts(6_120_000, 0)
    }
}
