// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for pallet_nft
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2026-02-02, STEPS: `100`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `ubuntu-8gb-nbg1-1-bench2`, CPU: `AMD EPYC-Milan Processor`

// Executed Command:
// ./polymesh
// benchmark
// pallet
// -s
// 100
// -r
// 5
// -p=*
// -e=*
// --heap-pages
// 4096
// --db-cache
// 512
// --execution
// wasm
// --wasm-execution
// compiled
// --output
// ./Polymesh/pallets/weights/src/
// --template
// ./.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_primitives::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_nft using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl pallet_nft::WeightInfo for SubstrateWeight {
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof: Identity KeyRecords (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: CddServiceProviders ActiveMembers (r:1 w:0)
    // Proof Skipped: CddServiceProviders ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:2 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: System BlockHash (r:1 w:0)
    // Proof: System BlockHash (max_values: None, max_size: Some(44), added: 2519, mode: MaxEncodedLen)
    // Storage: Asset AssetNonce (r:1 w:1)
    // Proof: Asset AssetNonce (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Nft CollectionAsset (r:1 w:1)
    // Proof: Nft CollectionAsset (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Asset AssetMetadataGlobalKeyToName (r:255 w:0)
    // Proof Skipped: Asset AssetMetadataGlobalKeyToName (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset Assets (r:1 w:1)
    // Proof Skipped: Asset Assets (max_values: None, max_size: None, mode: Measured)
    // Storage: ProtocolFee Coefficient (r:1 w:0)
    // Proof: ProtocolFee Coefficient (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: ProtocolFee BaseFees (r:1 w:0)
    // Proof: ProtocolFee BaseFees (max_values: None, max_size: Some(25), added: 2500, mode: MaxEncodedLen)
    // Storage: Identity CurrentPayer (r:1 w:0)
    // Proof: Identity CurrentPayer (max_values: Some(1), max_size: Some(32), added: 527, mode: MaxEncodedLen)
    // Storage: ExternalAgents NumFullAgents (r:1 w:1)
    // Proof: ExternalAgents NumFullAgents (max_values: None, max_size: Some(36), added: 2511, mode: MaxEncodedLen)
    // Storage: Nft CurrentCollectionId (r:1 w:1)
    // Proof: Nft CurrentCollectionId (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: Asset AssetNames (r:0 w:1)
    // Proof Skipped: Asset AssetNames (max_values: None, max_size: None, mode: Measured)
    // Storage: Asset SecurityTokensOwnedByUser (r:0 w:1)
    // Proof: Asset SecurityTokensOwnedByUser (max_values: None, max_size: Some(65), added: 2540, mode: MaxEncodedLen)
    // Storage: Asset AssetIdentifiers (r:0 w:1)
    // Proof Skipped: Asset AssetIdentifiers (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents AgentOf (r:0 w:1)
    // Proof: ExternalAgents AgentOf (max_values: None, max_size: Some(80), added: 2555, mode: MaxEncodedLen)
    // Storage: ExternalAgents GroupOfAgent (r:0 w:1)
    // Proof: ExternalAgents GroupOfAgent (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
    // Storage: Nft Collection (r:0 w:1)
    // Proof: Nft Collection (max_values: None, max_size: Some(48), added: 2523, mode: MaxEncodedLen)
    // Storage: Nft CollectionKeys (r:0 w:1)
    // Proof Skipped: Nft CollectionKeys (max_values: None, max_size: None, mode: Measured)
    /// The range of component `n` is `[1, 255]`.
    fn create_nft_collection(n: u32) -> Weight {
        // Minimum execution time: 130_276 nanoseconds.
        Weight::from_ref_time(140_592_380)
            // Standard Error: 10_470
            .saturating_add(Weight::from_ref_time(2_523_465).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(14))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(12))
    }
    // Storage: Nft CollectionAsset (r:1 w:0)
    // Proof: Nft CollectionAsset (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof: Identity KeyRecords (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: CddServiceProviders ActiveMembers (r:1 w:0)
    // Proof Skipped: CddServiceProviders ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:2 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents GroupOfAgent (r:1 w:0)
    // Proof: ExternalAgents GroupOfAgent (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
    // Storage: Permissions CurrentPalletName (r:1 w:0)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:0)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Nft CollectionKeys (r:1 w:0)
    // Proof Skipped: Nft CollectionKeys (max_values: None, max_size: None, mode: Measured)
    // Storage: Nft NFTsInCollection (r:1 w:1)
    // Proof: Nft NFTsInCollection (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Nft NumberOfNFTs (r:1 w:1)
    // Proof: Nft NumberOfNFTs (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Nft CurrentNFTId (r:1 w:1)
    // Proof: Nft CurrentNFTId (max_values: None, max_size: Some(32), added: 2507, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioNFT (r:0 w:1)
    // Proof: Portfolio PortfolioNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Nft MetadataValue (r:0 w:255)
    // Proof Skipped: Nft MetadataValue (max_values: None, max_size: None, mode: Measured)
    // Storage: Nft NFTOwner (r:0 w:1)
    // Proof: Nft NFTOwner (max_values: None, max_size: Some(121), added: 2596, mode: MaxEncodedLen)
    // Storage: Nft Owner (r:0 w:1)
    // Proof: Nft Owner (max_values: None, max_size: Some(122), added: 2597, mode: MaxEncodedLen)
    /// The range of component `n` is `[1, 255]`.
    fn issue_nft(n: u32) -> Weight {
        // Minimum execution time: 82_345 nanoseconds.
        Weight::from_ref_time(91_600_015)
            // Standard Error: 34_294
            .saturating_add(Weight::from_ref_time(3_096_680).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(13))
            .saturating_add(DbWeight::get().writes(6))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(n.into())))
    }
    // Storage: Nft CollectionAsset (r:1 w:0)
    // Proof: Nft CollectionAsset (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof: Identity KeyRecords (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: CddServiceProviders ActiveMembers (r:1 w:0)
    // Proof Skipped: CddServiceProviders ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:2 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents GroupOfAgent (r:1 w:0)
    // Proof: ExternalAgents GroupOfAgent (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
    // Storage: Permissions CurrentPalletName (r:1 w:0)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:0)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:1 w:0)
    // Proof: Portfolio PortfolioCustodian (max_values: None, max_size: Some(105), added: 2580, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioNFT (r:1 w:1)
    // Proof: Portfolio PortfolioNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioLockedNFT (r:1 w:0)
    // Proof: Portfolio PortfolioLockedNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Nft NFTsInCollection (r:1 w:1)
    // Proof: Nft NFTsInCollection (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Nft NumberOfNFTs (r:1 w:1)
    // Proof: Nft NumberOfNFTs (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Nft MetadataValue (r:256 w:255)
    // Proof Skipped: Nft MetadataValue (max_values: None, max_size: None, mode: Measured)
    // Storage: Nft NFTOwner (r:0 w:1)
    // Proof: Nft NFTOwner (max_values: None, max_size: Some(121), added: 2596, mode: MaxEncodedLen)
    // Storage: Nft Owner (r:0 w:1)
    // Proof: Nft Owner (max_values: None, max_size: Some(122), added: 2597, mode: MaxEncodedLen)
    /// The range of component `n` is `[1, 255]`.
    fn redeem_nft(n: u32) -> Weight {
        // Minimum execution time: 95_975 nanoseconds.
        Weight::from_ref_time(95_640_264)
            // Standard Error: 8_987
            .saturating_add(Weight::from_ref_time(4_685_714).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(15))
            .saturating_add(DbWeight::get().reads((1_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(5))
            .saturating_add(DbWeight::get().writes((1_u64).saturating_mul(n.into())))
    }
    // Storage: Nft CollectionAsset (r:1 w:0)
    // Proof: Nft CollectionAsset (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Nft NumberOfNFTs (r:2 w:2)
    // Proof: Nft NumberOfNFTs (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioNFT (r:10 w:20)
    // Proof: Portfolio PortfolioNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioLockedNFT (r:10 w:0)
    // Proof: Portfolio PortfolioLockedNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Asset Frozen (r:1 w:0)
    // Proof: Asset Frozen (max_values: None, max_size: Some(33), added: 2508, mode: MaxEncodedLen)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: CddServiceProviders ActiveMembers (r:1 w:0)
    // Proof Skipped: CddServiceProviders ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:4 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: ComplianceManager AssetCompliances (r:1 w:0)
    // Proof Skipped: ComplianceManager AssetCompliances (max_values: None, max_size: None, mode: Measured)
    // Storage: Nft NFTOwner (r:0 w:10)
    // Proof: Nft NFTOwner (max_values: None, max_size: Some(121), added: 2596, mode: MaxEncodedLen)
    // Storage: Nft Owner (r:0 w:10)
    // Proof: Nft Owner (max_values: None, max_size: Some(122), added: 2597, mode: MaxEncodedLen)
    /// The range of component `n` is `[1, 10]`.
    fn base_nft_transfer(n: u32) -> Weight {
        // Minimum execution time: 129_254 nanoseconds.
        Weight::from_ref_time(120_492_305)
            // Standard Error: 132_618
            .saturating_add(Weight::from_ref_time(16_928_598).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(11))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(2))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(n.into())))
    }
    // Storage: Identity KeyRecords (r:1 w:0)
    // Proof: Identity KeyRecords (max_values: None, max_size: Some(73), added: 2548, mode: MaxEncodedLen)
    // Storage: Timestamp Now (r:1 w:0)
    // Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    // Storage: CddServiceProviders ActiveMembers (r:1 w:0)
    // Proof Skipped: CddServiceProviders ActiveMembers (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Identity Claims (r:2 w:0)
    // Proof Skipped: Identity Claims (max_values: None, max_size: None, mode: Measured)
    // Storage: ExternalAgents GroupOfAgent (r:1 w:0)
    // Proof: ExternalAgents GroupOfAgent (max_values: None, max_size: Some(77), added: 2552, mode: MaxEncodedLen)
    // Storage: Permissions CurrentPalletName (r:1 w:0)
    // Proof Skipped: Permissions CurrentPalletName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Permissions CurrentDispatchableName (r:1 w:0)
    // Proof Skipped: Permissions CurrentDispatchableName (max_values: Some(1), max_size: None, mode: Measured)
    // Storage: Portfolio Portfolios (r:1 w:0)
    // Proof Skipped: Portfolio Portfolios (max_values: None, max_size: None, mode: Measured)
    // Storage: Portfolio PortfolioCustodian (r:1 w:0)
    // Proof: Portfolio PortfolioCustodian (max_values: None, max_size: Some(105), added: 2580, mode: MaxEncodedLen)
    // Storage: Nft CollectionAsset (r:1 w:0)
    // Proof: Nft CollectionAsset (max_values: None, max_size: Some(40), added: 2515, mode: MaxEncodedLen)
    // Storage: Nft NumberOfNFTs (r:2 w:2)
    // Proof: Nft NumberOfNFTs (max_values: None, max_size: Some(72), added: 2547, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioNFT (r:10 w:20)
    // Proof: Portfolio PortfolioNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Portfolio PortfolioLockedNFT (r:10 w:0)
    // Proof: Portfolio PortfolioLockedNFT (max_values: None, max_size: Some(114), added: 2589, mode: MaxEncodedLen)
    // Storage: Nft NFTOwner (r:0 w:10)
    // Proof: Nft NFTOwner (max_values: None, max_size: Some(121), added: 2596, mode: MaxEncodedLen)
    // Storage: Nft Owner (r:0 w:10)
    // Proof: Nft Owner (max_values: None, max_size: Some(122), added: 2597, mode: MaxEncodedLen)
    /// The range of component `n` is `[1, 10]`.
    fn controller_transfer(n: u32) -> Weight {
        // Minimum execution time: 94_662 nanoseconds.
        Weight::from_ref_time(85_354_998)
            // Standard Error: 134_878
            .saturating_add(Weight::from_ref_time(16_946_102).saturating_mul(n.into()))
            .saturating_add(DbWeight::get().reads(13))
            .saturating_add(DbWeight::get().reads((2_u64).saturating_mul(n.into())))
            .saturating_add(DbWeight::get().writes(2))
            .saturating_add(DbWeight::get().writes((4_u64).saturating_mul(n.into())))
    }
}
