// This file is part of the Polymesh distribution (https://github.com/PolymeshAssociation/Polymesh).
// Copyright (c) 2023 Polymesh

//! Autogenerated weights for pallet_indices
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 54.0.0
//! DATE: 2026-05-11, STEPS: `100`, REPEAT: 5, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `ubuntu-8gb-hel1-bench`, CPU: `AMD EPYC-Milan Processor`

// Executed Command:
// ./target/release/polymesh
// benchmark
// pallet
// -s
// 100
// -r
// 5
// -p=pallet_indices
// -e=*
// --heap-pages
// 4096
// --db-cache
// 512
// --output
// ./pallets/weights/src/
// --template
// ./.maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_primitives::{RocksDbWeight as DbWeight, Weight};

/// Weights for pallet_indices using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl pallet_indices::WeightInfo for SubstrateWeight {
    // Storage: `Indices::Accounts` (r:1 w:1)
    // Proof: `Indices::Accounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
    fn claim() -> Weight {
        // Minimum execution time: 25_590 nanoseconds.
        Weight::from_parts(27_850_000, 0)
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: `Indices::Accounts` (r:1 w:1)
    // Proof: `Indices::Accounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
    // Storage: `System::Account` (r:1 w:1)
    // Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn transfer() -> Weight {
        // Minimum execution time: 39_370 nanoseconds.
        Weight::from_parts(42_299_000, 0)
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: `Indices::Accounts` (r:1 w:1)
    // Proof: `Indices::Accounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
    fn free() -> Weight {
        // Minimum execution time: 25_549 nanoseconds.
        Weight::from_parts(27_520_000, 0)
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: `Indices::Accounts` (r:1 w:1)
    // Proof: `Indices::Accounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
    // Storage: `System::Account` (r:1 w:1)
    // Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    fn force_transfer() -> Weight {
        // Minimum execution time: 29_040 nanoseconds.
        Weight::from_parts(31_409_000, 0)
            .saturating_add(DbWeight::get().reads(2))
            .saturating_add(DbWeight::get().writes(2))
    }
    // Storage: `Indices::Accounts` (r:1 w:1)
    // Proof: `Indices::Accounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
    fn freeze() -> Weight {
        // Minimum execution time: 28_699 nanoseconds.
        Weight::from_parts(30_910_000, 0)
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().writes(1))
    }
    // Storage: `Indices::Accounts` (r:1 w:1)
    // Proof: `Indices::Accounts` (`max_values`: None, `max_size`: Some(69), added: 2544, mode: `MaxEncodedLen`)
    fn poke_deposit() -> Weight {
        // Minimum execution time: 25_290 nanoseconds.
        Weight::from_parts(27_300_000, 0)
            .saturating_add(DbWeight::get().reads(1))
            .saturating_add(DbWeight::get().writes(1))
    }
}
