// This file is part of Substrate.

// Copyright (C) 2021 Parity Technologies (UK) Ltd.
// SPDX-License-Identifier: Apache-2.0

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

//! Autogenerated weights for polymesh_transaction_payment
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 32.0.0
//! DATE: 2026-01-02, STEPS: `10`, REPEAT: 3, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: , WASM-EXECUTION: Compiled, CHAIN: None, DB CACHE: 512
//! HOSTNAME: `trance`, CPU: `AMD Ryzen 9 9950X3D 16-Core Processor`

// Executed Command:
// target/release/polymesh
// benchmark
// pallet
// -s
// 10
// -r
// 3
// -p=polymesh_transaction_payment
// -e=*
// --db-cache
// 512
// --heap-pages
// 4096
// --execution
// wasm
// --wasm-execution
// compiled
// --output
// ./
// --template
// .maintain/frame-weight-template.hbs

#![allow(unused_parens)]
#![allow(unused_imports)]

use polymesh_primitives::{RocksDbWeight as DbWeight, Weight};

/// Weights for polymesh_transaction_payment using the Substrate node and recommended hardware.
pub struct SubstrateWeight;
impl polymesh_transaction_payment::WeightInfo for SubstrateWeight {
    // Storage: `TransactionPayment::NextFeeMultiplier` (r:1 w:0)
    // Proof: `TransactionPayment::NextFeeMultiplier` (`max_values`: Some(1), `max_size`: Some(16), added: 511, mode: `MaxEncodedLen`)
    // Storage: `Relayer::Subsidies` (r:1 w:0)
    // Proof: `Relayer::Subsidies` (`max_values`: None, `max_size`: Some(96), added: 2571, mode: `MaxEncodedLen`)
    // Storage: `System::Account` (r:1 w:1)
    // Proof: `System::Account` (`max_values`: None, `max_size`: Some(128), added: 2603, mode: `MaxEncodedLen`)
    // Storage: `Authorship::Author` (r:1 w:0)
    // Proof: `Authorship::Author` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    // Storage: `System::Digest` (r:1 w:0)
    // Proof: `System::Digest` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
    // Storage: `Identity::CurrentPayer` (r:0 w:1)
    // Proof: `Identity::CurrentPayer` (`max_values`: Some(1), `max_size`: Some(32), added: 527, mode: `MaxEncodedLen`)
    fn charge_transaction_payment() -> Weight {
        // Minimum execution time: 27_252 nanoseconds.
        Weight::from_parts(28_203_000, 0)
            .saturating_add(DbWeight::get().reads(5))
            .saturating_add(DbWeight::get().writes(2))
    }
}
